
 
<!-- ******************************************************************************************************************************** -->
<!-- MODAL WINDOW DESIGN AND DEFINITIONS -->
<!-- ******************************************************************************************************************************** -->
	
	<!-- pencil Modal -->
	<div class="modal modal-wide fade" id="modalEditCustomerNotes" tabindex="-1" role="dialog" aria-labelledby="modalEditCustomerNotesLabel">
	
		<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 35px !important;
		}
		</style>
		
		<div class="modal-dialog" role="document">
							
			<div class="modal-content">	
	
				<input type="hidden" name="txtCategoryID" id="txtCategoryID">
				<input type="hidden" name="txtCustIDToPassToGenerateNotes" id="txtCustIDToPassToGenerateNotes">
				    
				<div id="modalEditCustomerNotesContent">
					<!-- Content for the modal will be generated and written here -->
					<!-- Content generated by Sub GetContentForCustomerNotesModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
				</div>
	
					  
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
				</div>
		
	
			</div>
			<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
	</div>
	<!-- eof modal !-->


	<!-- modal placeholder for edit prospect BusinessCard begins here !-->
	 <!-- Modal -->
	 
		<div class="modal fade" id="modalEditARCustomer" tabindex="-1" role="dialog" aria-labelledby="modalEditARCustomerLabel">		
		  <div class="modal-dialog" role="document" style="width:800px;">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="modalEditARCustomerInfoAddLabel">Update <%= GetTerm("Customer") %></h4>
		      </div>
		      <form name="frmEditCustomerFromModal" id="frmEditCustomerFromModal" action="<%= BaseURL %>accountsreceivable/customermininfo/editCustomerSubmit.asp" method="POST" onsubmit="return validateEditCustomer();">
		      		
		      	  <input type="hidden" name="txtInternalRecordIdentifier" id="txtInternalRecordIdentifier" value="<%= InternalRecordIdentifier %>">
		      	  <input type="hidden" name="txtCustIDOriginal" id="txtCustIDOriginal" value="<%= customerID %>">
		      	  <input type="hidden" name="txtCompanyNameOriginal" id="txtCompanyNameOriginal" value="<%= CustomerName %>">
		      	  <input type="hidden" name="txtLastPriceChangeDateOriginal" id="txtLastPriceChangeDateOriginal" value="<%= LastPriceChangeDate %>">

		      	  		      
			      <div class="modal-body">  
					<div class="row">					
						<div class="col-lg-12" style="margin-bottom:15px;" id="customerInfo"></div>							
			  			</div>
			       </div>
				   <div class="clearfix"></div>
						  

			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			        <button type="submit" class="btn btn-primary">Update <%= GetTerm("Customer") %></button>
			      </div>
		      </form>
		    </div>
		  </div>
		</div>
	<!-- modal ends here !-->
	<!-- edit prospect BusinessCard modal ends here !-->
	
	
	<!-- modal placeholder for edit customer pricing !-->
	 <!-- Modal -->
	 
		<div class="modal fade" id="modalEditLastPriceChangeDate" tabindex="-1" role="dialog" aria-labelledby="modalEditLastPriceChangeDateLabel">		
		  <div class="modal-dialog" role="document" style="width:800px;">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="modalEditLastPriceChangeDateAddLabel">Update Last Price Change Date</h4>
		      </div>
		      <form name="frmEditCustomerPricingFromModal" id="frmEditCustomerPricingFromModal" action="<%= BaseURL %>accountsreceivable/customermininfo/editCustomerPricingSubmit.asp" method="POST">
		      		
		      	  <input type="hidden" name="txtLastPriceChangeDateOriginal" id="txtLastPriceChangeDateOriginal" value="<%= LastPriceChangeDate %>">
		      
			      <div class="modal-body">  
					<div class="row">					
						<div class="col-lg-12" style="margin-bottom:15px;" id="customerPricingInfo"></div>							
			  			</div>
			       </div>
				   <div class="clearfix"></div>
						  

			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			        <button type="submit" class="btn btn-primary">Update <%= GetTerm("Customer") %> Price Change</button>
			      </div>
		      </form>
		    </div>
		  </div>
		</div>
	<!-- modal ends here !-->
	<!-- modal placeholder for edit customer pricing !-->
	
<!-- ******************************************************************************************************************************** -->
<!-- END MODAL WINDOW DESIGN AND DEFINITIONS -->
<!-- ******************************************************************************************************************************** -->


