<!-- **************************************************************************************************************************** -->
<!-- MODALS FOR REPORT SCHEDULERS START HERE !-->
<!-- **************************************************************************************************************************** -->

<!-- pencil Modal -->
<div class="modal fade" id="modalAutomaticCustomerAnalysisSummary1ReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalAutomaticCustomerAnalysisSummary1ReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleAutomaticCustomerAnalysisSummary1ReportSchedulerLabel">Automatic Customer Analysis 1 Report Generation Scheduler</h4>
		    </div>

			<form name="frmEditAutomaticCustomerAnalysisSummary1ReportSchedulerModal" id="frmEditAutomaticCustomerAnalysisSummary1ReportSchedulerModal" action="bizintel-automatic-customer-analysis-summary1-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalAutomaticCustomerAnalysisSummary1ReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForAutomaticCustomerAnalysisSummary1ReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnAutomaticCustomerAnalysisSummary1ReportScheduleSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- pencil Modal -->
<div class="modal fade" id="modalMCSActivityReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalMCSActivityReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleMCSActivityReportSchedulerLabel">MCS Activity Report Generation Scheduler</h4>
		    </div>

			<form name="frmEditMCSActivityReportSchedulerModal" id="frmEditMCSActivityReportSchedulerModal" action="bizintel-mcs-activity-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalMCSActivityReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForMCSActivityReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnMCSActivityReportScheduleSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Automatic Customer Analysis Summary 1 -->
<!-- Modal for Selecting Users -->
<div class="modal fade" id="modalCustAnalSum1EmailToUserNos" tabindex="-1" role="dialog" aria-labelledby="modalCustAnalSum1EmailToUserNosLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H1">Select users to send a report to:</h4>
		    </div>

			<form  onsubmit="$('#lstSelectedCustAnalSum1UserIDs option').prop('selected', true);"  name="frmEditUsersList" id="Form1" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="CustAnalSum1EmailToUserNos" />
				<div class="modal-body">
				    
					<div id="modalCustAnalSum1EmailToUserNosContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForCustAnalSum1EmailToUserNos() in InSightFuncs_AjaxForAdminSelectUsers.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button1" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<div class="modal fade" id="modalCustAnalSum1EmailAddressesToCC" tabindex="-1" role="dialog" aria-labelledby="modalCustAnalSum1EmailAddressesToCCLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="H2">Send report to the following additional email addresses</h4>
		    </div>

			<form name="frmEditCustAnalSum1EmailAddressesToCC" id="frmEditCustAnalSum1EmailAddressesToCC" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="CustAnalSum1EmailAddressesToCC" />
				<div class="modal-body">
				    
					<div id="Div4">
						<p>Cc: the following email addresses on this report
						<br><small>&nbsp;(Cc:'s will receive a separate email for each recipient of this report)</small>
						</p>
						<textarea class="form-control email-alert-line" rows="5" id="txtCustAnalSum1EmailAddressesToCC" name="txtCustAnalSum1EmailAddressesToCC"><%= CustAnalSum1EmailAddressesToCC %></textarea>
						<strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button2" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>

<!-- Modal for Selecting Users -->
<div class="modal fade" id="modalCustAnalSum1UserNosToCC" tabindex="-1" role="dialog" aria-labelledby="modalCustAnalSum1UserNosToCCLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H3">Select additional users to Cc:</h4>
               	<small>&nbsp;(Cc:'s will receive a separate email for each recipient of this report)</small>				
		    </div>

			<form  onsubmit="$('#lstSelectedCustAnalSum1CCUserIDs option').prop('selected', true);"  name="frmEditUsersList" id="Form2" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="CustAnalSum1UserNosToCC" />
				<div class="modal-body">
				    
					<div id="modalCustAnalSum1UserNosToCCContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForCustAnalSum1UserNosToCC() in InSightFuncs_AjaxForAdminSelectUsers.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button3" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Modal for Selecting Users -->
<div class="modal fade" id="modalMCSUserNosToCC" tabindex="-1" role="dialog" aria-labelledby="modalMCSUserNosToCCLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H4">Select additional users to Cc:</h4>    
		    </div>

			<form  onsubmit="$('#lstSelectedMCSCCUserIDs option').prop('selected', true);"  name="frmEditUsersList" id="Form3" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="MCSUserNosToCC" />
				<div class="modal-body">
				    
					<div id="modalMCSUserNosToCCContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForMCSUserNosToCC() in InSightFuncs_AjaxForAdminSelectUsers.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button4" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- MCS Activity Report -->
<!-- Modal for Selecting Users -->
<div class="modal fade" id="modalMCSActivitySummaryEmailToUserNos" tabindex="-1" role="dialog" aria-labelledby="modalMCSActivitySummaryEmailToUserNosLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H5">Select users to send a report to:</h4>
		    </div>

			<form  onsubmit="$('#lstSelectedMCSActivitySummaryUserIDs option').prop('selected', true);"  name="frmEditUsersList" id="Form4" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="MCSActivitySummaryEmailToUserNos" />
				<div class="modal-body">
				    
					<div id="modalMCSActivitySummaryEmailToUserNosContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForMCSActivitySummaryEmailToUserNos() in InSightFuncs_AjaxForAdminSelectUsers.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button5" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Modal for Selecting CC Emails -->
<div class="modal fade" id="modalMCSActivitySummaryEmailAddressesToCC" tabindex="-1" role="dialog" aria-labelledby="modalMCSActivitySummaryEmailAddressesToCCLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H6">Cc: the following email addresses on this report:</h4>
               	<small>&nbsp;(Cc:'s will receive a separate email for each recipient of this report)</small>				
		    </div>

			<form  name="frmEditUsersList" id="Form5" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="MCSActivitySummaryEmailAddressesToCC" />
				<div class="modal-body">
				    
					<div id="Div2">
						<textarea class="form-control email-alert-line" rows="5" id="Textarea1" name="txtMCSActivitySummaryEmailAddressesToCC"><%= MCSActivitySummaryEmailAddressesToCC %></textarea>
						<strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button6" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Modal for Selecting additional Users -->
<div class="modal fade" id="modalMCSActivitySummaryUserNosToCC" tabindex="-1" role="dialog" aria-labelledby="modalMCSActivitySummaryUserNosToCCLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H7">Select additional users to Cc:</h4>
               	<small>&nbsp;(Cc:'s will receive a separate email for each recipient of this report)</small>
		    </div>

			<form  onsubmit="$('#lstSelectedMCSActivitySummaryCCUserIDs option').prop('selected', true);"  name="frmEditUsersList" id="Form6" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="MCSActivitySummaryUserNosToCC" />
				<div class="modal-body">
				    
					<div id="modalMCSActivitySummaryUserNosToCCContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForMCSActivitySummaryUserNosToCC() in InSightFuncs_AjaxForAdminSelectUsers.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button7" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- **************************************************************************************************************************** -->
<!-- MODALS FOR REPORT SCHEDULERS END HERE !-->
<!-- **************************************************************************************************************************** -->
