

<!-- **************************************************************************************************************************** -->
<!-- MODALS FOR REPORT SCHEDULERS START HERE !-->
<!-- **************************************************************************************************************************** -->


<!-- CarryOver Report ----->
<!-- Modal for Selecting Users -->
<div class="modal fade" id="modalCarryoverReportTeamIntRecIDs" tabindex="-1" role="dialog" aria-labelledby="modalCarryoverReportTeamIntRecIDsLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="H3">Select teams to send a summary report to:</h4>
                <p>
			        	<small>(For each customer who has a service ticket appearing on this report, an email will be sent to the team members for their collective customer accounts.
			        	The team selected below will recieve an overall summary report of all open tickets)</small></p>
		    </div>

			<form onsubmit="$('#lstSelectedServiceTicketCarryoverReportTeamIntRecIDs option').prop('selected', true);" name="frmEditUsersTeamsListCarryover" id="frmEditUsersTeamsListCarryover" action="users-teams-list-update.asp" method="POST">
                <input type="hidden" name="userTeamListName" value="CarryoverReportTeamIntRecIDs" />
				<div class="modal-body">
				    
					<div id="modalCarryoverReportTeamIntRecIDsContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForCarryoverReportTeamIntRecIDs() in InSightFuncs_AjaxForAdminSelectUsers.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="ButtonTeamCarryover" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


<!-- pencil Modal -->
<div class="modal fade" id="modalFieldServiceNotesReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalFieldServiceNotesReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleFieldServiceNotesReportSchedulerSchedulerLabel"><%= GetTerm("Field Service") %> Notes Report Generation Scheduler</h4>
		    </div>

			<form name="frmEditFieldServiceNotesReportSchedulerModal" id="frmEditFieldServiceNotesReportSchedulerModal" action="field-service-notes-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalFieldServiceNotesReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForFieldServiceNotesReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnFieldServiceNotesReportSchedulerSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->
            

<!-- pencil Modal -->
<div class="modal fade" id="modalServiceTicketCarryoverReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalServiceTicketCarryoverReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleServiceTicketCarryoverReportSchedulerLabel">Service Ticket Carryover Report Schedule</h4>
		    </div>

			<form name="frmEditServiceTicketCarryoverReportSchedulerModal" id="frmEditServiceTicketCarryoverReportSchedulerModal" action="field-service-carryover-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalServiceTicketCarryoverReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceTicketCarryoverReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnServiceTicketCarryoverReportScheduleSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- pencil Modal -->
<div class="modal fade" id="modalServiceTicketThresholdReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalServiceTicketThresholdReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleServiceTicketThresholdReportSchedulerLabel">Service Ticket Threshold Report Schedule</h4>
		    </div>

			<form name="frmEditServiceTicketThresholdReportSchedulerModal" id="frmEditServiceTicketThresholdReportModal" action="service-ticket-Threshold-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalServiceTicketThresholdReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceTicketThresholdReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnServiceTicketThresholdReportSchedulerSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


<!-- Modal for Additional Emails -->
<div class="modal fade" id="modalNotesReportAdditionalEmails" tabindex="-1" role="dialog" aria-labelledby="modalNotesReportAdditionalEmailsLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="H2">Send report to the following additional email addresses</h4>
		    </div>

			<form name="frmEditAdditionalNotesReportEmails" id="Form1" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="NotesReportAdditionalEmails" />
				<div class="modal-body">
				    
					<div id="Div2">
						<textarea class="form-control email-alert-line" rows="5" id="txtFieldServiceNotesReportAdditionalEmails" name="txtFieldServiceNotesReportAdditionalEmails"><%= FieldServiceNotesReportAdditionalEmails %></textarea>
				        <strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button1" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>



<div class="modal fade" id="modalCarryoverReportAdditionalEmails" tabindex="-1" role="dialog" aria-labelledby="modalCarryoverReportAdditionalEmailsLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="H4">Send report to the following additional email addresses</h4>
		    </div>

			<form name="frmEditAdditionalCarryoverReportEmails" id="frmEditAdditionalCarryoverReportEmails" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="CarryoverReportAdditionalEmails" />
				<div class="modal-body">
				    
					<div id="Div3">
						<textarea class="form-control email-alert-line" rows="5" id="txtServiceTicketCarryoverReportAdditionalEmails" name="txtServiceTicketCarryoverReportAdditionalEmails"><%= ServiceTicketCarryoverReportAdditionalEmails%></textarea>
						<strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button3" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>

<div class="modal fade" id="modalThresholdReportAdditionalEmails" tabindex="-1" role="dialog" aria-labelledby="modalThresholdReportAdditionalEmailsLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="H6">Send report to the following additional email addresses</h4>
		    </div>

			<form name="frmEditAdditionalThresholdReportEmails" id="frmEditAdditionalThresholdReportEmails" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="ThresholdReportAdditionalEmails" />
				<div class="modal-body">
				    
					<div id="Div6">
						<textarea class="form-control email-alert-line" rows="5" id="txtServiceTicketThresholdReportAdditionalEmails" name="txtServiceTicketThresholdReportAdditionalEmails"><%= ServiceTicketThresholdReportAdditionalEmails%></textarea>
						<strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button5" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>


<!-- **************************************************************************************************************************** -->
<!-- MODALS FOR REPORT SCHEDULERS END HERE !-->
<!-- **************************************************************************************************************************** -->
