
<!-- **************************************************************************************************************************** -->
<!-- MODALS FOR REPORT SCHEDULERS START HERE !-->
<!-- **************************************************************************************************************************** -->

<!-- pencil Modal -->
<div class="modal fade" id="modalDailyAPIActivityByPartnerReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalDailyAPIActivityByPartnerReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleDailyAPIActivityByPartnerReportSchedulerLabel">Daily <%= GetTerm("Inventory") %> API Activity By Partner Report Generation Scheduler</h4>
		    </div>

			<form name="frmEditDailyAPIActivityByPartnerReportSchedulerModal" id="frmEditDailyAPIActivityByPartnerReportSchedulerModal" action="inventory-daily-activity-by-partner-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalDailyAPIActivityByPartnerReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForInventoryDailyAPIActivityByPartnerReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnDailyAPIActivityByPartnerReportScheduleSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


<!-- pencil Modal -->
<div class="modal fade" id="modalInventoryProductChangesReportScheduler" tabindex="-1" role="dialog" aria-labelledby="modalInventoryProductChangesReportSchedulerLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="titleInventoryProductChangesReportSchedulerLabel"><%= GetTerm("Inventory") %> Product Changes Report Generation Scheduler</h4>
		    </div>

			<form name="frmEditInventoryProductChangesReportSchedulerModal" id="frmEditInventoryProductChangesReportSchedulerModal" action="inventory-product-changes-report-scheduler-submit.asp" method="POST">

				<div class="modal-body">
				    
					<div id="modalInventoryProductChangesReportSchedulerContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForInventoryProductChangesReportScheduler() in InSightFuncs_AjaxForAdminTimepickerModals.asp -->
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="btnInventoryProductChangesReportScheduleSave" class="btn btn-primary">Save Schedule Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- Daily Inventory API Activity Summary By Partner Report ----->
<div class="modal fade" id="modalInventoryAPIDailyActivityReportAdditionalEmails" tabindex="-1" role="dialog" aria-labelledby="modalInventoryAPIDailyActivityReportAdditionalEmailsLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="H6">Send report to the following additional email addresses</h4>
		    </div>

			<form name="frmEditInventoryAPIDailyActivityReportAdditionalEmails" id="frmEditInventoryAPIDailyActivityReportAdditionalEmails" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="InventoryAPIDailyActivityReportAdditionalEmails" />
				<div class="modal-body">
				    
					<div id="Div6">
						<textarea class="form-control email-alert-line" rows="5" id="Textarea1" name="txtInventoryAPIDailyActivityReportAdditionalEmails"><%= InventoryAPIDailyActivityReportAdditionalEmails %></textarea>
						<strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button5" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>



<!-- Inventory Product Changes Report -->
<div class="modal fade" id="modalInventoryProductChangesReportAdditionalEmails" tabindex="-1" role="dialog" aria-labelledby="modalInventoryProductChangesReportAdditionalEmailsLabel">
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
	
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="H2">Send report to the following additional email addresses</h4>
		    </div>

			<form name="frmEditInventoryProductChangesReportAdditionalEmails" id="frmEditmodalInventoryProductChangesReportAdditionalEmails" action="users-list-update.asp" method="POST">
                <input type="hidden" name="userListName" value="InventoryProductChangesReportAdditionalEmails" />
				<div class="modal-body">
				    
					<div id="Div4">
						<textarea class="form-control email-alert-line" rows="5" id="txtInventoryProductChangesReportAdditionalEmails" name="txtInventoryProductChangesReportAdditionalEmails"><%= InventoryProductChangesReportAdditionalEmails %></textarea>
						<strong>Separate multiple email addresses with a semicolon</strong>
					</div>
						
				</div>
				<!-- eof modal body !-->
				
				 <div class="clearfix"></div>
			      
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
					<button type="submit" id="Button2" class="btn btn-primary">Save Changes</button>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>


<!-- **************************************************************************************************************************** -->
<!-- MODALS FOR REPORT SCHEDULERS END HERE !-->
<!-- **************************************************************************************************************************** -->
