


<!-- Edit Existing Filter Modal -->
<div class="modal fade" id="modalEditSageInvoice" tabindex="-1" role="dialog" aria-labelledby="modalEditSageInvoiceLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<style>
				.modal-header {
				    padding: 15px;
				    border-bottom: 1px solid #e5e5e5;
				}
		
				.title-right {
					position:relative;
					right:0;
					top:0;
					width:40%;
					color:#FF0000;
					display: inline-block;"
				}
				.title-left {
					position:relative;
					left:0;
					top:0;
					width:55%;
					display: inline-block;"			
				}		
				.modalrow {
					    border-bottom: 1px solid #ddd !important;	
					    padding-bottom:20px;	
					    padding-top:20px;		
			    }
			    .width25 {
					width:25%;
					display:inline;
				}

			    .width50 {
					width:50%;
					display:inline;
				}

			    .width75 {
					width:75%;
					display:inline;
				}
			
			</style>
			<div id="modalEditSageInvoiceContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForEditSageInvoiceModal() in InSightFuncs_AjaxForARAP.asp -->				
			</div>
				
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



