
<!-- **************************************************************************************************************************** -->
<!-- MODAL FOR SERVICE BOARD OPTIONS BEGIN HERE !-->
<!-- **************************************************************************************************************************** -->


<div class="modal fade" id="serviceBoardTicketOptionsModal" tabindex="-1" role="dialog" aria-labelledby="serviceBoardLabel">

	<div class="modal-dialog" role="document">
	
		<style>
		
			.btn-huge{
			    padding-top:20px;
			    padding-bottom:20px;
			    margin-bottom:10px;
			}
			
			.center {
			    margin-left:50px;
			}	
					
			.auto-style1 {
				text-align: right;
			}
		</style>
							
		<div class="modal-content">
	    
			<!-- modal header !-->
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close" id="btnCloseFromTop"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="serviceBoardLabel"></h4>
			</div>
			<!-- eof modal header !-->
	  
			<!-- modal body !-->
			<div class="modal-body">
			
					<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
					<input type="hidden" name="txtCustID" id="txtCustID" value="">
					<input type="hidden" name="txtUserNo" id="txtUserNo" value="">
				
					<div id="ServiceBoardTicketOptionsModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceBoardTicketOptionsModal() in InsightFuncs_AjaxForServiceModals.asp -->
					</div>
			</div>
			
		
			<!-- modal footer !-->
		    <div class="modal-footer">
				      			      	      
				<!-- close / save !-->
				<div class="col-lg-12">
					<button type="button" class="btn btn-default" data-dismiss="modal" id="btnCloseFromBottom">Close</button>
				</div>
				<!-- eof close / save !-->
		
			</div>
			<!-- eof modal footer !-->
			

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->





<div class="modal fade" id="serviceBoardSetAlertModal" tabindex="-1" role="dialog" aria-labelledby="serviceBoardSetAlertLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
		
			<form method="post" action="#" name="frmSetAlertModal" id="frmSetAlertModal">
		    
				<!-- modal header !-->
				<div class="modal-header">		
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="serviceBoardSetAlertModalTitle">Set Alert (Coming Soon)</h4>
				</div>
				<!-- eof modal header !-->
		  
				<!-- modal body !-->
				<div class="modal-body">
				
					<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
					
					<div id="ServiceBoardSetAlertModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceBoardSetAlertModal() in InsightFuncs_AjaxForServiceModals.asp -->
						sdfsdfsdfsdf
					</div>
				</div>
			
				<!-- modal footer !-->
			    <div class="modal-footer">
					      			      	      
					<!-- close / save !-->
					<div class="col-lg-12">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">SET ALERT</button>
					</div>
					<!-- eof close / save !-->
			
				</div>
				<!-- eof modal footer !-->
				
			</form>

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->





<div class="modal fade" id="serviceBoardXferModal" tabindex="-1" role="dialog" aria-labelledby="serviceBoardXferModalLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
				
			<form method="post" action="serviceBoardXferRedispatchModal_SaveValues.asp" name="frmXferRedispatchModal" id="frmXferRedispatchModal">
						    
				<!-- modal header !-->
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="ServiceBoardXferModalTitle"></h4>
				</div>
				<!-- eof modal header !-->
				
	
				<div class="modal-body">
					<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
					<input type="hidden" name="txtCustID" id="txtCustID" value="">
					<input type="hidden" name="txtUserNo" id="txtUserNo" value="">
		
					<div id="ServiceBoardXferModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceBoardTransferRedispatchModal() in InsightFuncs_AjaxForServiceModals.asp -->
					</div>
				</div>
					      
				<div class="modal-footer" style="margin-top: 325px;">
					<div class="col-lg-12">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-primary">REASSIGN</button>
					</div>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->		
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->
		


<div class="modal fade" id="serviceBoardRequestETAModal" tabindex="-1" role="dialog" aria-labelledby="serviceBoardRequestETALabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
		
			<form method="post" action="#" name="frmRequestETAModa" id="frmRequestETAModa">
	    
				<!-- modal header !-->
				<div class="modal-header">		
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="serviceBoardRequestETAModalTitle">Request ETA(Coming Soon)</h4>
				</div>
				<!-- eof modal header !-->
		  
				<!-- modal body !-->
				<div class="modal-body">
				
					<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
					
					<div id="ServiceBoardRequestETAModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceBoardRequestETAModal() in InsightFuncs_AjaxForServiceModals.asp -->
						sdfsdfsdfsdf
					</div>
				</div>
			
				<!-- modal footer !-->
			    <div class="modal-footer">
					      			      	      
					<!-- close / save !-->
					<div class="col-lg-12">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">REQUEST ETA</button>
					</div>
					<!-- eof close / save !-->
			
				</div>
				<!-- eof modal footer !-->
				
			</form>

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<div class="modal fade" id="serviceBoardChangeTypeModal" tabindex="-1" role="dialog" aria-labelledby="serviceBoardChangeTypeModalLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
				
			<form method="post" action="serviceBoardChangeTypeModal_SaveValues.asp" name="frmChangeTypeModal" id="frmChangeTypeModal">
						    
				<!-- modal header !-->
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="ServiceBoardChangeTypeModalTitle"></h4>
				</div>
				<!-- eof modal header !-->
				
	
				<div class="modal-body">
					<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
					<input type="hidden" name="txtCustID" id="txtCustID" value="">
		
					<div id="ServiceBoardChangeTypeModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceBoardChangeTypeModal() in InsightFuncs_AjaxForServiceModals.asp -->
					</div>
				</div>
					      
				<div class="modal-footer" style="margin-top: 325px;">
					<div class="col-lg-12">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-primary">Save</button>
					</div>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->		
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


<div class="modal fade" id="serviceBoardDispatchModal" tabindex="-1" role="dialog" aria-labelledby="serviceBoardDispatchModalLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
				
			<form method="post" action="serviceBoardDispatchModal_SaveValues.asp" name="frmDispatchModal" id="frmDispatchModal">
						    
				<!-- modal header !-->
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="ServiceBoardDispatchModalTitle"></h4>
				</div>
				<!-- eof modal header !-->
				
	
				<div class="modal-body">
					<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
					<input type="hidden" name="txtCustID" id="txtCustID" value="">
		
					<div id="ServiceBoardDispatchModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForServiceBoardDispatchModal() in InsightFuncs_AjaxForServiceModals.asp -->
					</div>
				</div>
					      
				<div class="modal-footer" style="margin-top: 325px;">
					<div class="col-lg-12">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-primary">Save</button>
					</div>
				</div>
				
			</form>

		</div>
		<!-- eof modal content !-->		
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="serviceBoardMarkAsUrgentWithTextingModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Text Message?</h4>
      </div>
      
      <div class="modal-body">
      	<p>Do you also want to send the technician a text message letting them know that this ticket has been changed to urgent?</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes-send-urgent-text">YES</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no-urgent-text">NO</button>
      </div>
      <!-- eof modal footer !-->
    </div>
    <!-- eof modal content !-->
  </div>
  <!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="serviceBoardMarkAsNotUrgentWithTextingModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Text Message?</h4>
      </div>
      
      <div class="modal-body">
      	<p>Do you also want to send the technician a text message letting them know that this ticket is no longer urgent?</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes-send-text">YES</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no-text">NO</button>
      </div>
      <!-- eof modal footer !-->
    </div>
    <!-- eof modal content !-->
  </div>
  <!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- pencil Modal -->
<div class="modal modal-wide fade" id="modalEditServiceTicketNotes" tabindex="-1" role="dialog" aria-labelledby="modalEditServiceTicketNotesLabel">

	<style>
	.modal-header {
	    padding: 15px;
	    border-bottom: 1px solid #e5e5e5;
	    min-height: 35px !important;
	}
	</style>
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<input type="hidden" name="txtTicketNumber" id="txtTicketNumber" value="">
			<input type="hidden" name="txtCustID" id="txtCustID" value="">
			<input type="hidden" name="txtUserNo" id="txtUserNo" value="">			
			    
			<div id="modalEditServiceTicketNotesContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForServiceTicketNotesModal() in InsightFuncs_AjaxForServiceModals.asp -->
			</div>

				  
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>
	

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- Add MCS Client Modal -->
<div class="modal modal-wide-autocomplete fade" id="modalCreateNewServiceTicketForClient" tabindex="-1" role="dialog" aria-labelledby="modalCreateNewServiceTicketForClient">

	<div class="modal-dialog" role="document">
						
	<div class="modal-content">	

	<% 
		ClientKeyForFileNames = MUV_READ("ClientKeyForFileNames")
		ClientKeyForFileNames = "1106d"	
	 %>
	
	<script type="text/javascript">
	
		var autocompleteJSONFileURLAccount = "<%= BaseURL %>clientfiles/<%= ClientKeyForFileNames %>/autocomplete/customer_account_list_CSZ_POS_<%= ClientKeyForFileNames %>.json";
	
		//common function to populate selectboxes
		function PopulateSelectBoxes(selectid){
		    $.ajax({
		        type: "POST",
		        url: 'onthefly_SelectBoxes.asp',
		        data: ({ section : selectid, action:'add' }),
		        dataType: "html",
		        success: function(data) {
		            $("#"+selectid).html(data);
		        },
		        error: function() {
		            alert('Error occured');
		        }
		    });	
		}
				
		$(document).ready(function(){
            
			var optionsAccount = {
			  url: autocompleteJSONFileURLAccount,
			  placeholder: "Search for a customer by name, account, city, state, zip",
			  getValue: "name",
			  list: {	
			  
				onClickEvent: function() {
			        //alert("click");
			        $(".easy-autocomplete-container ul").hide();
			    },		  
		        onChooseEvent: function() {
		            var custID = $("#txtCustIDAutocomplete").getSelectedItemData().code;
		            $("#txtCustIDToPass").val(custID);
		            
					 if (custID!=""){
					 	$.ajax({
							type:"POST",
							url: "../inc/InSightFuncs_AjaxForServiceModals.asp",
							data: "action=GetContentForCreateServiceTicketModal&custID="+encodeURIComponent(custID),
							success: function(msg){
								$("#selectedCustomerInfoForm").html(msg);
								$("#btnCreateNewServiceTicketForClientSave").show();
								
								// below code added by nurba
								// 03/15/2019					 
								 PopulateSelectBoxes('txtEquipmentSymptom');	  
												 
							 	//-------------------------------------------------------------------------------
								// Equipment symptom select box change
							    $("#txtEquipmentSymptom").change(function() {
									var val = $( "#txtEquipmentSymptom option:selected").val();
									if (val== -1){
										//deselect add new row
										$('#txtEquipmentSymptom option[selected="selected"]').each(
											function() {
												$(this).removeAttr('selected');
											}
										);
							
										// mark the first option as selected
										$("#txtEquipmentSymptom option:first").attr('selected','selected');
										
										//show modal
										//$('#myProspectingModalEditBusinessCard').modal('hide');
										$('#ONTHEFLYmodalSymptomCode').modal('show');
										
									}
								});
									
								
								//Industry modal window submit
								$('#frmAddSymptomCode').submit(function(e) {
									
									if ($('#frmAddSymptomCode #txtSymptomDescription').val()==''){
										 swal("Symptom description cannot be blank.");
										return false;
									}
									
									$("#ONTHEFLYmodalSymptomCode .btn-primary").html("Saving...");
							        $.ajax({
							            type: "POST",
							            url: "onthefly_SymptomCodes_submit.asp",
							            data: $('#frmAddSymptomCode').serialize(),
							            success: function(response) {
											PopulateSelectBoxes('txtEquipmentSymptom');
											$("#ONTHEFLYmodalSymptomCode .modal-body").html('Symptom added successfully<br><br><button type="button" class="btn btn-default" data-dismiss="modal" aria-label="Close">Close</button>');
											
							            },
							            error: function() {
											$("#ONTHEFLYmodalSymptomCode .btn-primary").html("Save");
							                //alert('Error adding symptom');
							            }
							        });
							        return false;
							    });
							//-------------------------------------------------------------------------------
							//end nurba

							}
						}) 
					  }
					  else {
					  	swal("Please select a customer account");
					  }
		            
	        	},		  
			    match: {
			      enabled: true
				},
				maxNumberOfElements: 30
			  },
			  theme: "round",
			  requestDelay: 500	
			};
			
			$("#txtCustIDAutocomplete").easyAutocomplete(optionsAccount);
		
			
			$("#btnCreateNewServiceTicketForClientSave").click(function() {
			  //$('#PleaseWaitPanelModalService').show();
			});	
					
					
		});
		
	
	    function validateServiceMemoform()
	    {
	
		   var txtEquipmentType = $("#txtEquipmentType option:selected").val();
		   
	       if (txtEquipmentType == "" || txtEquipmentType == "-1") {
	            swal("Please select an equipment type from the list below.");
	            document.frmAddServiceMemo.txtEquipmentType.focus();
	            return false;
	       }
			      		    				       
		   var txtEquipmentSymptom = $("#txtEquipmentSymptom option:selected").val();
		   
	       if (txtEquipmentSymptom == "" || txtEquipmentSymptom == "-1") {
	            swal("Please select a symptom of the equipment problem.");
	            document.frmAddServiceMemo.txtEquipmentSymptom.focus();
	            return false;
	       }
	        	
		   var txtDateProblemStarted = $("#txtDateProblemStarted").val();
		   		    
	       if (txtDateProblemStarted == "") {
	            swal("Please select the approximate date the problem started.");
	            document.frmAddServiceMemo.txtDateProblemStarted.focus();
	            return false;
	       }
	        
	        if (document.frmAddServiceMemo.txtWhoToContactUponArrival.value == "") {
	            swal("Please enter the name of the individual to contact upon arrival.");
	            document.frmAddServiceMemo.txtWhoToContactUponArrival.focus();
	            return false;
	        }
	
	        if (document.frmAddServiceMemo.txtContactPhone.value == "") {
	            swal("Please enter the phone number of the contact person.");
	            document.frmAddServiceMemo.txtContactPhone.focus();
	            return false;
	        }

	        if (document.frmAddServiceMemo.txtContactEmail.value == "") {
	            swal("Please enter the email address of the contact person.");
	            document.frmAddServiceMemo.txtContactEmail.focus();
	            return false;
	        }
	
	        if (document.frmAddServiceMemo.txtFloorSuite.value == "") {
	            swal("Please enter a location (floor/suite).");
	            document.frmAddServiceMemo.txtFloorSuite.focus();
	            return false;
	        }
	        
	        if (document.frmAddServiceMemo.txtDescription.value == "") {
	            swal("Problem description cannot be blank.");
	            document.frmAddServiceMemo.txtDescription.focus();
	            return false;
	        }
	        
	        $('#selectedCustomerInfoForm').hide();
	        $('#PleaseWaitPanelModalService').show();
	        return true;	
	    }
		
	</script>
	
	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		#searchIcon {
		    position: relative;
		    z-index: 1000000;
		    color: #888;
		    top: -35px;
		    left: 880px;
		}	
		.table-info .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{
			border: 0px;
			font-weight: bold;
			line-height: 0.8;
		}
		.alert{
	 		padding: 6px 12px;
		}
		
		.form-control{
			margin-bottom: 20px;
		}
		
		a:hover{
			text-decoration: none;
		}
		
	    .well {
	    	margin-left:20px;
	    	margin-right:20px;
		}
		
		.easy-autocomplete {
		  z-index: 1000000;
		}		
		
		.easy-autocomplete.eac-round {
		  font-family: "Open Sans", "Helvetica Neue",Helvetica,Arial,sans-serif;
		}
		.easy-autocomplete.eac-round input {
		  border: 2px solid #888;
		  border-radius: 10px;
		  color: #888;
		  font-family: inherit;
		  font-size: 12px;
		  font-weight: 400;
		  margin: 0;
		  min-width: 300px;
		  padding: 10px;
		}
		.easy-autocomplete.eac-round input:hover, .easy-autocomplete.eac-round input:focus {
		  border-color: #3079ed;
		}

		.easy-autocomplete-container ul {
		  background: none repeat scroll 0 0 #ffffff;
		  border-top: 1px dotted #ccc;
		  display: none;
		  margin-top: 0;
		  padding-bottom: 0;
		  padding-left: 0;
		  position: relative;
		  top: -1px;
		  max-height: 300px; /* Set your expected height */
		  overflow: auto; 
		  overflow-y: auto;  /* Enable vertical scrollbar */
		  overflow-x:hidden;		  
		}
		
		.easy-autocomplete.eac-round ul {
		  background: none;
		  border-color: #888;
		  border-width: 0;
		  box-shadow: none;
		  top: 20px;
		  max-width:900px;
		  z-index:9999 !important;
		}
				
		.easy-autocomplete.eac-round ul li, .easy-autocomplete.eac-round ul .eac-category {
		  background: #fff;
		  border-color: #3079ed;
		  border-width: 0 2px;
		  font-size: 12px;
		  padding: 8px 12px;
		  transition: all 0.4s ease 0s;
		}
	
	</style>
			
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title" id="modalCreateNewServiceTicketForClientTitle"><i class="fa fa-wrench"></i> Submit A New Service Ticket</h4>
	</div>

	<form method="POST" action="addServiceMemo_postandsubmit.asp" name="frmAddServiceMemo" onsubmit="return validateServiceMemoform();">
	
		<div class="modal-body modalResponsiveTable">
			<div id="modalCreateNewServiceTicketForClientContent">
			
				<div class="row">
					<div class="col-lg-12">
						<!-- select Client !-->
						<input id="txtCustIDAutocomplete" name="txtCustIDAutocomplete" style="width:920px;z-index:9999 !important;">
						<input type="hidden" id="CreateNewServiceTicketForClientCustIDToPass" name="txtCustIDToPass" value="">
						<i id="searchIcon" class="fa fa-search fa-2x"></i>
						<!-- eof select Client !-->
					</div>
				</div>

				<div id="PleaseWaitPanelModalService" style="display:none;">
					<br><br><strong>Submitting Service Ticket, Please Wait...</strong><br><br>
					<img src="<%= BaseURL %>img/loading.gif">
				</div>	
				
				<div id="selectedCustomerInfoForm">
				</div>
		
			</div>
		</div>
	
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			<button type="submit" class="btn btn-primary" style="display:none;" id="btnCreateNewServiceTicketForClientSave" name="btnCreateNewServiceTicketForClientSave"><i class="fa fa-upload"></i> Submit Ticket</button>				
		</div>
		
	</form>
		
	</div>
	<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->







<!-- Edit Service Ticket Modal -->
<div class="modal modal-wide-autocomplete fade" id="modalEditExistingServiceTicketForClient" tabindex="-1" role="dialog" aria-labelledby="modalEditExistingServiceTicketForClient">

	<div class="modal-dialog" role="document">
						
	<div class="modal-content">	
	
	
	<script type="text/javascript">
	
		
		//$("#btnEditExistingServiceTicketForClientSave").click(function() {
			//$('#PleaseWaitPanelModalService').show();
		//});
			
	
	    function validateCloseCancelServiceMemoForm()
	    {
	        	
		   var CloseCancelDate = $("#txtCloseCancelDate").val();
		   		    
	       if (CloseCancelDate == "") {
	            swal("Please select the date to close/cancel this ticket.");
	            document.frmEditServiceMemo.txtCloseCancelDate.focus();
	            return false;
	       }

		   var CloseCancelTime = $("#timepicker").val();
		   		    
	       if (CloseCancelTime == "") {
	            swal("Please select the time to close/cancel this ticket.");
	            document.frmEditServiceMemo.timepicker.focus();
	            return false;
	       }

	       var optCloseOrCancel = $('input[name="optCloseOrCancel"]:checked').val();
	       	       
	       if (optCloseOrCancel == "Close") {
	       
			   var EquipmentProblem = $("#txtEquipmentProblem option:selected").val();
			   
		       if (EquipmentProblem == "" || EquipmentProblem == "-1") {
		            swal("Please select a problem for this ticket.");
		            document.frmEditServiceMemo.txtEquipmentProblem.focus();
		            return false;
		       }
		       
			   var EquipmentResolution = $("#txtEquipmentResolution option:selected").val();
			   
		       if (EquipmentResolution == "" || EquipmentResolution == "-1") {
		            swal("Please select a Resolution for this ticket.");
		            document.frmEditServiceMemo.txtEquipmentResolution.focus();
		            return false;
		       }
		   }

			
			if ($('#selFieldTech').length)
			{
			   var FieldServiceTech = $("#selFieldTech option:selected").val();
			   
		       if (FieldServiceTech == "" || FieldServiceTech == "-1" || FieldServiceTech == "Select Field Tech") {
		            swal("Please select a field service technician.");
		            document.frmEditServiceMemo.selFieldTech.focus();
		            return false;
		       }
	       
			}
			
		   var ServiceNotes = $("#ServiceNotes").val();
		   		    
	       if (ServiceNotes == "") {
	            swal("Please enter notes before closing or cancelling this ticket.");
	            document.frmEditServiceMemo.ServiceNotes.focus();
	            return false;
	       }
	       
	       $('#selectedTicketNumberInformation').hide();
	       $('#PleaseWaitPanelModalServiceCloseCancel').show();
	       
	       return true;	
	    }
		
	</script>
	
	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		.table-info .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{
			border: 0px;
			font-weight: bold;
			line-height: 0.8;
		}
		.alert{
	 		padding: 6px 12px;
		}
		
		.form-control{
			margin-bottom: 20px;
		}
		
		a:hover{
			text-decoration: none;
		}
		
	    .well {
	    	margin-left:20px;
	    	margin-right:20px;
		}
		
		.yellow{
			background-color:#FEFC9F;
		}

		.ui-timepicker-table td a{
			padding: 3px;
			width:auto;
			text-align: left;
			font-size: 11px;
		}	
		
		.ui-timepicker-table .ui-timepicker-title{
			font-size: 13px;
		}
		
		.ui-timepicker-table th.periods{
			font-size: 13px;
		}
		
		.ui-widget-header{
			background: #193048;
			border: 1px solid #193048;
		}
		
		 .custom-hr{
			height: 3px;
			margin-left: auto;
			margin-right: auto;
			background-color:#183049;
			color:#183049;
			border: 0 none;
		}
		
		.control-label{
			padding-top: 5px;
		}
		
		.do-not-send-alert{
		 	padding: 5px 10px 5px 10px;
			display: inline-block;
			background: #fff200;
		}
		
		.the-information{
			font-size:12px;
			margin-top:20px;
		} 
		
		.date-col{
			width:15%;
		} 
		
		.stage-col{
			width:10%;
		} 
		
		.user-col{
			width:10%;
		} 
		
		.alert{
			display:block;
			float:left;
			margin:0px 5px 5px 0px;
		}

		#accordion .panel,
		#accordion .panel-heading,
		#accordion panel-title,
		#accordion .panel-body {
		  border: 0;
		}
		#accordion .panel {
		  box-shadow: none;
		}
		#accordion .panel .panel-heading {
		  border-radius: 0;
		}
		#accordion .panel .panel-heading .panel-title a {
		  text-decoration: none;
		  padding: 1em 0;
		}
		#accordion .panel .panel-heading .panel-title a span {
		  float: right;
		  width: 50px;
		}
		#accordion .panel .panel-heading .panel-title a span:after {
		  content: "\2014";
		  color: #1B5062;
		  font-size: 20px;
		}
		#accordion .panel .panel-heading .panel-title a.collapsed span:after {
		  content: "+";
		}	
	</style>
			
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<div class="modal-title" id="modalEditExistingServiceTicketForClientTitle"></div>
	</div>

	<form method="POST" action="<%= BaseURL %>service/editservicememo_submit.asp" name="frmEditServiceMemo" id="frmEditServiceMemo" onsubmit="return validateCloseCancelServiceMemoForm();">
	
		<input type="hidden" id="txtPrintedName" name="txtPrintedName" value="N/A Closed From MDS Insight">
		<input type="hidden" id="txtMemoNumber" name="txtMemoNumber">
		<input type="hidden" id="txtCustIDCloseCancel" name="txtCustIDCloseCancel">
		<input type="hidden" id="txtReturnPathCloseCancel" name="txtReturnPathCloseCancel">
	
		<div class="modal-body modalResponsiveTable">
			<div id="modalEditExistingServiceTicketForClientContent">
			
				<div id="PleaseWaitPanelModalServiceCloseCancel" style="display:none;">
					<br><br><strong>Submitting Service Ticket, Please Wait...</strong><br><br>
					<img src="<%= BaseURL %>img/loading.gif">
				</div>	
				
				<div id="selectedTicketNumberInformation">
				</div>
		
			</div>
		</div>
	
		<div class="modal-footer">
		    <button type="button" class="btn btn-default" data-dismiss="modal">&lsaquo; Cancel</button>			    
			<button type="submit" class="btn btn-primary" style="display:none;" id="btnEditExistingServiceTicketForClientSave" name="btnEditExistingServiceTicketForClientSave"><i class="fa fa-upload"></i> Submit Ticket</button>				
		</div>
		
	</form>
		
	</div>
	<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->







<!-- View Closed Service Ticket Modal -->
<div class="modal modal-wide-autocomplete fade" id="modalViewOpenClosedServiceTicketDetailsForClient" tabindex="-1" role="dialog" aria-labelledby="modalViewOpenClosedServiceTicketDetailsForClient">

	<div class="modal-dialog" role="document">
						
	<div class="modal-content">	
	
	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		.table-info .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{
			border: 0px;
			font-weight: bold;
			line-height: 0.8;
		}
		.alert{
	 		padding: 6px 12px;
		}
		
		.form-control{
			margin-bottom: 20px;
		}
		
		a:hover{
			text-decoration: none;
		}
		
	    .well {
	    	margin-left:20px;
	    	margin-right:20px;
		}
		
		.yellow{
			background-color:#FEFC9F;
		}
		
		.control-label{
			padding-top: 5px;
		}
		
		.the-information{
			font-size:12px;
			margin-top:20px;
		} 
		
		.date-col{
			width:15%;
		} 
		
		.stage-col{
			width:10%;
		} 
		
		.user-col{
			width:10%;
		} 
		
		.alert{
			display:block;
			float:left;
			margin:0px 5px 5px 0px;
		}

		.fancybox-custom .fancybox-skin {
			box-shadow: 0 0 50px #222;
		}
	
		.thumbnail{
			max-width: 100px;
			max-height: 100px;
			display: inline;
			margin-left:15px;
		}
	
		.thumbnail-signature{
			max-width: 300px;
			max-height: 200px;
			display: inline;
			margin-left:15px;
			border:1px teal dashed;
		}
		
		.thumbnail-photos{
			float: left;
			margin: 10px;
			margin-top:20px;
		}
		
		#lightbox .modal-content {
	    display: inline-block;
	    text-align: center;   
		}
	
		#lightbox .close {
		    opacity: 1;
		    color: rgb(255, 255, 255);
		    background-color: rgb(25, 25, 25);
		    padding: 5px 8px;
		    border-radius: 30px;
		    border: 2px solid rgb(255, 255, 255);
		    position: absolute;
		    top: -15px;
		    right: -55px;
		    
		    z-index:1032;
		}
		
	</style>
			
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title" id="modalViewOpenClosedServiceTicketDetailsForClientTitle"><i class="fa fa-wrench"></i> View Service Ticket</h4>
	</div>

		<input type="hidden" id="txtMemoNumberView" name="txtMemoNumberView">
		<input type="hidden" id="txtCustIDView" name="txtCustIDView">
		<input type="hidden" id="txtPrintedNameView" name="txtPrintedNameView" value="N/A Closed From MDS Insight">

	
		<div class="modal-body modalResponsiveTable">
			<div id="modalViewOpenClosedServiceTicketDetailsForClientContent">
				
				<div id="selectedOpenClosedTicketNumberInformation">
				</div>
		
			</div>
		</div>
	
		<div class="modal-footer">
		    <button type="button" class="btn btn-default" data-dismiss="modal">&lsaquo; Close Ticket Window</button>			    
		</div>
		
	</div>
	<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


<!-- **************************************************************************************************************************** -->
<!-- MODAL FOR SERVICE BOARD OPTIONS END HERE !-->
<!-- **************************************************************************************************************************** -->
