
<!-- pencil Modal -->
<div class="modal modal-wide fade" id="modalEditCustomerNotes" tabindex="-1" role="dialog" aria-labelledby="modalEditCustomerNotesLabel">

	<style>
	.modal-header {
	    padding: 15px;
	    border-bottom: 1px solid #e5e5e5;
	    min-height: 35px !important;
	}
	</style>
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<input type="hidden" name="txtCategoryID" id="txtCategoryID">
			<input type="hidden" name="txtCustIDToPassToGenerateNotes" id="txtCustIDToPassToGenerateNotes">
			    
			<div id="modalEditCustomerNotesContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForCustomerNotesModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
			</div>

				  
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>
	

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- modal -->
<div class="modal fade" id="modalMemos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Memos</h4>
      </div>
      <div class="modal-body">
        Memos content goes here.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- eof modal -->






<!-- Equipment Modal -->
<div class="modal modal-xwide fade" id="modalEquipmentVPC" tabindex="-1" role="dialog" aria-labelledby="modalEquipmentVPCLabel">

	<div class="modal-dialog" role="document">
	
	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}
		
		.tile {
		  width: 6%;
		  display: inline-block;
		  box-sizing: border-box;
		  background: #fff;
		  padding-top: 10px;
		  padding-top: 10px;
		  padding-left: 5px;
		  color:#FFF;
		}
		
		.tile .title {
		  margin-top: 0px;
		}
		
		.tile.red {
		  background: #AC193D;
		  color:#FFF;
		}
		
		.tile.red:hover {
		  background: #7f132d;
		  color:#FFF;
		}
		
		.tile.blue {
		  background: #2672EC;
		  color:#FFF;
		}
		
		.tile.blue:hover {
		  background: #125acd;
		  color:#FFF;
		}
		
		.equip_qty{
			font-weight:bold;
			font-size:1.2em;
	
		}
		
	</style>
						
		<div class="modal-content">	
		
			<input type="hidden" name="txtCustIDToPass" id="txtCustIDToPass">
			<input type="hidden" name="txtLastClosedPeriodGP" id="txtLastClosedPeriodGP">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalEquipmentVPCTitle"><!-- Content generated by Sub GetTitleForEquipmentVPCModal() in InsightFuncs_AjaxForBizIntelModals.asp --></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
			
				<div id="PleaseWaitPanelModal">
				<br><br><strong>Analyzing Equipment for <%= CustName %>, please wait...</strong><br><br>
				<img src="<%= BaseURL %>img/loading.gif">
				</div>	
			
				<div id="modalCategoryVPCContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForEquipmentVPCModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->





<!-- modal -->
<div class="modal fade bs-example-modal-lg" id="modalServiceTickets" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Service Tickets</h4>
      </div>
      <div class="modal-body">
        Service Tickets content goes here.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- eof modal -->



<!-- modal -->
<div class="modal fade bs-example-modal-lg" id="modalXPage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">X Page</h4>
      </div>
      <div class="modal-body">
        X Page content goes here.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- eof modal -->


<!-- VPC Modal -->
<div class="modal modal-xwide fade" id="modalCategoryVPC" tabindex="-1" role="dialog" aria-labelledby="modalCategoryVPCLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
		
			<input type="hidden" name="txtCategoryID" id="txtCategoryID">
			<input type="hidden" name="txtCustIDToPass" id="txtCustIDToPass">
			<input type="hidden" name="txtPeriodSeqToPass" id="txtPeriodSeqToPass">
			<input type="hidden" name="txtVarianceBasisToPass" id="txtVarianceBasisToPass">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalCategoryVPCTitle"></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalCategoryVPCContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForCategoryVPCModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- General Notes Group M Modal -->
<div class="modal fade" id="modalGeneralNotesGroupM" tabindex="-1" role="dialog" aria-labelledby="modalGeneralNotesGroupMLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		.title-right {
			position:relative;
			right:0;
			top:0;
			width:40%;
			color:#FF0000;
			display: inline-block;"
		}
		.title-left {
			position:relative;
			left:0;
			top:0;
			width:55%;
			display: inline-block;"			
		}		
	
	</style>
			<input type="hidden" name="GNGMCustIDToPass" id="GNGMCustIDToPass">
			<input type="hidden" name="GNGMuserno" id="GNGMuserno">
			<input type="hidden" name="GNGMMSCMonth" id="GNGMMSCMonth">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalGeneralNotesGroupMTitle"><div class="title-left"><span id="GNGMcustname"></span></div><div class="title-right"><span id="GNGMvariance"></span></div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalGeneralNotesGroupMContent">
					<table class="table-condensed table-hover large-table">			
						<tbody>
							<tr>
								<td><input type="radio" name="groupm" value="no_action_necessary" checked> No action necessary at this time.</td><td><select id="GNGMReasons"><option value="selectreason">Select Reason</option></select></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm" value="remove_client"> Remove this client from the MCS program<br></td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm" value="change_mcs"> Change this client's MCS to:</td>
								<td>$&nbsp;<input type="text" class="" id="GNGMchange_mcs" size="17" value=""></td>
								<td>&nbsp;</td>
							</tr>							
							<tr>
								<td><input type="radio" name="groupm" value="change_lvf"> Change the maximum LVF for this client to :</td>
								<td>$&nbsp;<input type="text" class="" id="GNGMchange_lvf" size="17" value=""></td><td class="smaller-detail-line"><span>&nbsp;</span></td>
								<td>&nbsp;</td>
							</tr>														
							<tr>
								<td><input type="radio" name="groupm" value="send_invoice"> Send this client an invoice for the following amount:</td>
								<td>$&nbsp;<input type="text" class="" id="GNGMinvoice_amount" size="17" value=""></td><td class="smaller-detail-line-r"><span id="maxallowed">Max Allowed</span></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm"  value="notify_selected_sales_person"> Notify the selected <%= GetTerm("salesperson") %> to followup on the MCS shortage: </td>
								<td><select id="GNGMsalesperson">
									<option id="GNGMsp1" value=""><%= GetTerm("Primary Salesman") %></option>
									<option id="GNGMsp2" value=""><%= GetTerm("Secondary Salesman") %></option>
									</select>
								</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm" value="send_message_to_someone"> Send someone a message about this client.</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>														
							<tr class="hidemsg">
								<td colspan=2>Inclue the following message with the followup email:<br>
									<textarea id="GNGMMsg" name="GNGMMsg" rows="5" cols="70"></textarea>
								</td>			
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="GNGMSave" name="GNGMSave" value="Save">Save</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Add MCS Client Modal -->
<div class="modal fade" id="modalAddMCSClient" tabindex="-1" role="dialog" aria-labelledby="modalAddMCSClient">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

<% ClientKeyForFileNames = MUV_READ("ClientKeyForFileNames") %>

<!---------------------------------------------------------------------------------------------------------->
<!----------THIS IS A CUSTOM STYLESHEET ADDED FOR THE AUTOCOMPLETE SEARCH FOR CATEGORY ANALYSIS ONLY-------->
<!-----------IT OVERRIDES THE STYLES THAT ARE STILL LOADED IN HEADER.ASP------------------------------------>

<!---------------------------------------------------------------------------------------------------------->
<link rel="stylesheet" href="http://dev.mdsinsight.com/js/easyautocomplete/EasyAutocomplete-1.4.0/easy-autocomplete-cat-analysis.css"> 

<!---------------------------------------------------------------------------------------------------------->
<!---------------------------------------------------------------------------------------------------------->
<!--
	js/easyautocomplete/EasyAutocomplete-1.4.0/easy-autocomplete.themes.css ALSO CONTAINS A CUSTOM STYLE
	SET CALLED "easy-autocomplete.eac-cat-analysis"
-->
<!---------------------------------------------------------------------------------------------------------->
<!---------------------------------------------------------------------------------------------------------->

<script type="text/javascript">

	var autocompleteJSONFileURLAccount = "/clientfiles/<%= ClientKeyForFileNames %>/autocomplete/customer_account_list_CSZ_<%= ClientKeyForFileNames %>.json";
	
$(document).ready(function(){

	var optionsAccount = {
	  url: autocompleteJSONFileURLAccount,
	  placeholder: "Search for a customer by name, account, city, state, zip",
	  getValue: "name",
	  list: {	
        onChooseEvent: function() {
        
            var custID = $("#txtCustID").getSelectedItemData().code;  
			$("#AddMCSClientCustNameToPass").val($("#txtCustID").getSelectedItemData().name.split(" --- ")[1])			
			$("#AddMCSClientCustIDToPass").val(custID);
			            		
            //window.location.href = "CatAnalByPeriod_SingleCustomer.asp?CID=" + custID + "&ZDC=0&VB=3Periods" + "&oon=" + oldornew;
			
            
    	},		  
	    match: {
	      enabled: true
		},
		maxNumberOfElements: 20		
	  },
	  theme: "cat-analysis"
	};
	$("#txtCustID").easyAutocomplete(optionsAccount);
			
});

</script>
	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		.easy-autocomplete.eac-round input{
			width: 100% !important;
		}
		.title-right {
			position:relative;
			right:0;
			top:0;
			width:40%;
			color:#FF0000;
			display: inline-block;"
		}
		.title-left {
			position:relative;
			left:0;
			top:0;
			width:55%;
			display: inline-block;"			
		}		
	
	</style>
				
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalAddMCSClientTitle"><div class="title-left"><span id="GNGMcustname"></span></div><div class="title-right"><span id="GNGMvariance"></span></div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalAddMCSClientContent">
					<table class="table-condensed table-hover large-table">			
						<tbody>				
							<tr>
								<td colspan="2">
									<!-- select Client !-->
										<input id="txtCustID" name="txtCustID">
										<input type="hidden" id="AddMCSClientCustIDToPass" name="txtCustIDToPass" value="" >
										<input type="hidden" id="AddMCSClientCustNameToPass" name="txtCustNameToPass" value="" >
										<i id="searchIcon" class="fa fa-search fa-2x"></i>
									<!-- eof select Client !-->		
								</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="AddMCSClientSave" name="AddMCSClientSave" value="Continue">Continue</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Add MCS Client Modal Setp 2 -->
<div class="modal fade" id="modalAddMCSClient2" tabindex="-1" role="dialog" aria-labelledby="modalAddMCSClient2Label">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
		<style>
		.error {
		  background: #AC193D;
		  color:#FFF;
		}
		</style>
			<input type="hidden" name="AddMCSClient2CustIDToPass" id="AddMCSClient2CustIDToPass">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalAddMCSClient2Title"><div class="title-left">Add Client <span id="AddMCSClient2custid"></span> - <span id="AddMCSClient2custname"></span> To MCS</div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalAddMCSClient2Content">
					<table class="table-condensed table-hover large-table">			
						<tbody>
							<tr>
								<td>Monthly contracted spend</td>
								<td>&nbsp;<input type="text" name="AddMCSClient2MonthlyContractedSalesDollars" id="AddMCSClient2MonthlyContractedSalesDollars"></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>Maximum MCS fee (if applicable)</td>
								<td>&nbsp;<input type="text" name="AddMCSClient2MaxMCSCharge" id="AddMCSClient2MaxMCSCharge"></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="AddMCSClient2Save" name="AddMCSClient2Save" value="Add">Add</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->	

<!-- Select User Modal -->
<div class="modal fade" id="modalSelectUser" tabindex="-1" role="dialog" aria-labelledby="modalSelectUserLabel">

	<div class="modal-dialog" role="document">
<script language="Javascript">

	function listbox_addSelectUser() {
	
		var src = document.getElementById("lstSelectUserIDs");
		var dest = document.getElementById("lstSelectedUserIDs");
	
		for(var count=0; count < src.options.length; count++) {
	
			if(src.options[count].selected == true) {
					var option = src.options[count];
	
					var newOption = document.createElement("option");
					newOption.value = option.value;
					newOption.text = option.text;
					newOption.selected = true;
					try {
							 dest.add(newOption, null); //Standard
							 src.remove(count, null);
					 }catch(error) {
							 dest.add(newOption); // IE only
							 src.remove(count);
					 }
					count--;
			}
		}
	}	

	function listbox_removeSelectUser() {
	
		//var src = document.getElementById("lstSelectUserIDs");
		//var dest = document.getElementById("lstSelectedUserIDs");

		var dest = document.getElementById("lstSelectUserIDs");
		var src = document.getElementById("lstSelectedUserIDs");
	
		for(var count=0; count < src.options.length; count++) {
	
			if(src.options[count].selected == true) {
					var option = src.options[count];
	
					var newOption = document.createElement("option");
					newOption.value = option.value;
					newOption.text = option.text;
					newOption.selected = true;
					try {
							 dest.add(newOption, null); //Standard
							 src.remove(count, null);
					 }catch(error) {
							 dest.add(newOption); // IE only
							 src.remove(count);

					 }
					count--;
			}
		}
	}
</script>			
			
<style>
	.keepcenter {
		text-align: center;
	}
</style>
		<div class="modal-content">	

			<input type="hidden" name="SUCustIDToPass" id="SUCustIDToPass">
			<input type="hidden" name="SUParamsFromParent" id="SUParamsFromParent">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalSelectUserTitle"><div class="title-left"><span id="SUcustname"></span></div><div class="title-right"><span id="SUvariance"></span></div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalSelectUserContent">
					<table class="table-condensed table-hover large-table table-width">			
						<tbody>
							<tr>
								<td colspan="3"><strong>Send this message to the following people</strong></td>
							</tr>
							<tr>
								<td colspan="3">Master User List</td>
							</tr>
							<tr>
								<td>
								<select multiple class="form-control multi-select" id="lstSelectUserIDs" name="lstSelectUserIDs" style="width: 200px; height: 300px;">
									<option>Select User</option>
								</select>
								</td>
								<td class="keepcenter"> 
									<a href="javascript:void(0)" onclick="javascript:listbox_addSelectUser()"><button type="button" class="btn btn-success" style="margin-bottom:10px;margin-top:40px;">Add User <i class="fa fa-arrow-right" aria-hidden="true"></i></button></a>
									<BR>
									<a href="javascript:void(0)" onclick="javascript:listbox_removeSelectUser()"><button type="button" class="btn btn-danger"><i class="fa fa-arrow-left" aria-hidden="true"></i> Remove User </button></a>
								</td>
								<td>
								<select multiple class="form-control multi-select" id="lstSelectedUserIDs" name="lstSelectedUserIDs"  style="width: 200px; height: 300px;">
								
								</select>
								</td>
							</tr>							
							<tr>
								<td colspan="3"><strong>Please enter your message in the box below</strong><br>
									<textarea id="SUMsg" name="SUMsg" rows="5" cols="70"></textarea>
								</td>			
							</tr>
							<tr>								
								<td colspan="3" class="keepcenter">
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="SUSave" name="SUSave" value="Save">Save</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->