<%
' This code is for the chart of Service Memos
SundayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-1)*-1,Date()),"OPEN")
SundayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-1)*-1,Date()),"CLOSE")
SundayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-1)*-1,Date()),"CANCEL")
SundayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-1)*-1,Date()),"OPEN")
MondayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-2)*-1,Date()),"OPEN")
MondayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-2)*-1,Date()),"CLOSE")
MondayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-2)*-1,Date()),"CANCEL")
MondayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-2)*-1,Date()),"OPEN")
TuesdayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-3)*-1,Date()),"OPEN")
TuesdayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-3)*-1,Date()),"CLOSE")
TuesdayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-3)*-1,Date()),"CANCEL")
TuesdayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-3)*-1,Date()),"OPEN")
WednesdayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-4)*-1,Date()),"OPEN")
WednesdayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-4)*-1,Date()),"CLOSE")
WednesdayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-4)*-1,Date()),"CANCEL")
WednesdayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-4)*-1,Date()),"OPEN")
ThursdayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-5)*-1,Date()),"OPEN")
ThursdayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-5)*-1,Date()),"CLOSE")
ThursdayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-5)*-1,Date()),"CANCEL")
ThursdayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-5)*-1,Date()),"OPEN")
FridayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-6)*-1,Date()),"OPEN")
FridayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-6)*-1,Date()),"CLOSE")
FridayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-6)*-1,Date()),"CANCEL")
FridayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-6)*-1,Date()),"OPEN")
SaturdayOpen = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-7)*-1,Date()),"OPEN")
SaturdayClose = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-7)*-1,Date()),"CLOSE")
SaturdayCancel = GetNumberOfTicketsByDate(DateAdd("d",(WeekDay(Date())-7)*-1,Date()),"CANCEL")
SaturdayDisp = GetNumberOfNONDispatchedTicketsByDate(DateAdd("d",(WeekDay(Date())-7)*-1,Date()),"OPEN")
DateRangeTitleForGraph = DateAdd("d",(WeekDay(Date())-1)*-1,Date()) & " - " & DateAdd("d",(WeekDay(Date())-7)*-1,Date())
%>
