
<!-- **************************************************************************************************************************** -->
<!-- MODAL FOR DELIVERY ALERTS BEGINS HERE !-->
<!-- **************************************************************************************************************************** -->


<div class="modal fade" id="deliveryBoardInvoiceOptionsModal" tabindex="-1" role="dialog" aria-labelledby="deliveryBoardLabel">

	<div class="modal-dialog" role="document">
	
		<style>
		
			.btn-huge{
			    padding-top:20px;
			    padding-bottom:20px;
			    margin-bottom:10px;
			}
			
			.center {
			    margin-left:50px;
			}	
					
			.auto-style1 {
				text-align: right;
			}
		</style>
							
		<div class="modal-content">
	    
			<!-- modal header !-->
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close" id="btnCloseFromTop"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="deliveryBoardLabel"></h4>
			</div>
			<!-- eof modal header !-->
	  
			<!-- modal body !-->
			<div class="modal-body">
			
					<input type="hidden" name="txtInvoiceNumber" id="txtInvoiceNumber" value="">
					<input type="hidden" name="txtCustID" id="txtCustID" value="">
					<input type="hidden" name="txtUserNo" id="txtUserNo" value="">

					<div id="deliveryBoardInvoiceOptionsModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForDeliveryBoardInvoiceOptionsModal() in InsightFuncs_AjaxForRoutingModals.asp -->
					</div>
			</div>
			
		
			<!-- modal footer !-->
		    <div class="modal-footer">
				      			      	      
				<!-- close / save !-->
				<div class="col-lg-12">
					<button type="button" class="btn btn-default" data-dismiss="modal" id="btnCloseFromBottom">Close</button>
				</div>
				<!-- eof close / save !-->
		
			</div>
			<!-- eof modal footer !-->
			

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<div class="modal fade" id="deliveryBoardAddAlertModal" tabindex="-1" role="dialog" aria-labelledby="myDeliveryBoardLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
	    
			<!-- modal header !-->
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myDeliveryBoardLabelAdd"></h4>
			</div>
			<!-- eof modal header !-->
	  
			<!-- modal body !-->
			<div class="modal-body">
			
				<input type="hidden" name="txtInvoiceNumber" id="txtInvoiceNumber" value="">
					<div id="deliveryBoardAddModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForAddDeliveryBoardAlertModal() in InsightFuncs_AjaxForRoutingModals.asp -->
					</div>
			</div>

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->




<div class="modal fade" id="deliveryBoardEditAlertModal" tabindex="-1" role="dialog" aria-labelledby="myDeliveryBoardLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
	    
			<!-- modal header !-->
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myDeliveryBoardLabelEdit"></h4>
			</div>
			<!-- eof modal header !-->
	  
			<!-- modal body !-->
			<div class="modal-body">
			
				<input type="hidden" name="txtInvoiceNumber" id="txtInvoiceNumber" value="">
					<div id="deliveryBoardEditModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForEditDeliveryBoardAlertModal() in InsightFuncs_AjaxForRoutingModals.asp -->
					</div>
			</div>

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<div class="modal fade" id="myDeliveryBoardCompletedOrSkippedModal" tabindex="-1" role="dialog" aria-labelledby="myDeliveryBoardCompletedOrSkippedLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">
	    
			<!-- modal header !-->
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myDeliveryBoardCompletedOrSkippedLabel"></h4>
			</div>
			<!-- eof modal header !-->
	  
			<!-- modal body !-->
			<div class="modal-body">
			
				<input type="hidden" name="txtInvoiceNumber" id="txtInvoiceNumber" value="">
					<div id="deliveryBoardCompletedOrSkippedModalContent">
						<!-- Content for the modal will be generated and written here -->
						<!-- Content generated by Sub GetContentForCompletedOrSkippedInfoModal() in InsightFuncs_AjaxForRoutingModals.asp -->
					</div>
			</div>

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->




<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel1" aria-hidden="true" id="deliveryBoardMarkAsPriorityWithTextingModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Text Message?</h4>
      </div>
      
      <div class="modal-body">
      	<p>Do you also want to send the driver a text message letting them know that this delivery has been changed to high priority?</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes-send-priority-text">YES, SEND TEXT</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no-priority-text">NO</button>
      </div>
      <!-- eof modal footer !-->
    </div>
    <!-- eof modal content !-->
  </div>
  <!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel2" aria-hidden="true" id="deliveryBoardMarkAsNotPriorityWithTextingModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Text Message?</h4>
      </div>
      
      <div class="modal-body">
      	<p>Do you also want to send the driver a text message letting them know that this delivery is no longer a priority?</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes-send-text">YES, SEND TEXT</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no-text">NO</button>
      </div>
      <!-- eof modal footer !-->
    </div>
    <!-- eof modal content !-->
  </div>
  <!-- eof modal dialog !-->
</div>
<!-- eof modal !-->




<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel3" aria-hidden="true" id="deliveryBoardMarkAsAMDeliveryWithTextingModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Text Message?</h4>
      </div>
      
      <div class="modal-body">
      	<p>Do you also want to send the driver a text message letting them know that this delivery has been changed to an AM Delivery?</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes-send-am-text">YES, SEND TEXT</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no-am-text">NO</button>
      </div>
      <!-- eof modal footer !-->
    </div>
    <!-- eof modal content !-->
  </div>
  <!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel4" aria-hidden="true" id="deliveryBoardRemoveAMDeliveryWithTextingModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Text Message?</h4>
      </div>
      
      <div class="modal-body">
      	<p>Do you also want to send the driver a text message letting them know that this delivery is no longer an AM Delivery?</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes-remove-am-send-text">YES, SEND TEXT</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no-remove-am-text">NO</button>
      </div>
      <!-- eof modal footer !-->
    </div>
    <!-- eof modal content !-->
  </div>
  <!-- eof modal dialog !-->
</div>
<!-- eof modal !-->




<!-- **************************************************************************************************************************** -->
<!-- MODAL FOR DELIVERY ALERTS ENDS HERE !-->
<!-- **************************************************************************************************************************** -->
