
<!-- pencil Modal -->
<div class="modal modal-wide fade" id="modalEditCategoryNotes" tabindex="-1" role="dialog" aria-labelledby="modalEditCategoryNotesLabel">

	<style>
	.modal-header {
	    padding: 15px;
	    border-bottom: 1px solid #e5e5e5;
	    min-height: 35px !important;
	}
	</style>
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<input type="hidden" name="txtCategoryID" id="txtCategoryID">
			<input type="hidden" name="txtCustIDToPass" id="txtCustIDToPass">
			    
			<div id="modalEditCategoryNotesContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForCategoryAnalysisByPeriodNotesModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
			</div>

				  
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>
	

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- Add Filter Modal -->
<div class="modal fade" id="modalAddFilter" tabindex="-1" role="dialog" aria-labelledby="modalAddFilterLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<style>
				.modal-header {
				    padding: 15px;
				    border-bottom: 1px solid #e5e5e5;
				    min-height: 135px;
				}
		
				.title-right {
					position:relative;
					right:0;
					top:0;
					width:40%;
					color:#FF0000;
					display: inline-block;"
				}
				.title-left {
					position:relative;
					left:0;
					top:0;
					width:55%;
					display: inline-block;"			
				}		
				.modalrow {
					    border-bottom: 1px solid #ddd !important;	
					    padding-bottom:20px;	
					    padding-top:20px;		
			    }
			    .width25 {
					width:25%;
					display:inline;
				}

			    .width50 {
					width:50%;
					display:inline;
				}

			    .width75 {
					width:75%;
					display:inline;
				}
			
			</style>
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalAddFilterTitle"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New Filter</h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">

	         	<div class="row modalrow">
	         	   	<div class="col-lg-4">Filter ID</div>
		         	<div class="col-lg-8">
						<input type="text" id="txtFilterID" name="txtFilterID" class="form-control">
					</div>
				</div>

	         	<div class="row modalrow">
	         	   	<div class="col-lg-4">Filter Description</div>
		         	<div class="col-lg-8">
						<textarea class="form-control" rows="4" id="txtFilterDescription" name="txtFilterDescription"></textarea>
					</div>
				</div>
				
	         	<div class="row modalrow">
	         	   	<div class="col-lg-6">Default Cost $&nbsp;<input type="text" id="txtFilterCost" name="txtFilterCost" class="form-control width75"></div>
	         	   	<div class="col-lg-6">List Price $&nbsp;<input type="text" id="txtFilterListPrice" name="txtFilterListPrice" class="form-control width75"></div>				
				</div>

	         	<div class="row modalrow">
	         	   	<div class="col-lg-2">Taxable?</div>
		         	<div class="col-lg-2">
						<select class="form-control" id="selFilterTaxable" name="selFilterTaxable">			
							<option value="1">Y</option>
							<option value="0" selected="selected">N</option>
						</select>
					</div>	         	
	         	   	<div class="col-lg-2">Inventoried?</div>
		         	<div class="col-lg-2">
						<select class="form-control" id="selFilterInventoried" name="selFilterInventoried">			
							<option value="1">Y</option>
							<option value="0" selected="selected">N</option>
						</select>
					</div>
	         	   	<div class="col-lg-2">Pickable?</div>
		         	<div class="col-lg-2">
						<select class="form-control" id="selFilterPickable" name="selFilterPickable">			
							<option value="1">Y</option>
							<option value="0" selected="selected">N</option>
						</select>
					</div>
				</div>

	         	<div class="row modalrow">
	         	   	<div class="col-lg-4">UPC Code</div>
		         	<div class="col-lg-8">
						<input type="text" id="txtFilterUPC" name="txtFilterUPC" class="form-control width75">
					</div>
				</div>

	         	<div class="row modalrow">
	         	   	<div class="col-lg-4">Prod ID</div>
		         	   	<div class="col-lg-8">
		         	   	<select class="form-control" id="selFilterprodSKU" name="selFilterprodSKU">		
			         	   	<option value="">NONE</option>
			         	   	<%
			         	 	Set cnnICFilters = Server.CreateObject("ADODB.Connection")
							cnnICFilters.open (Session("ClientCnnString"))
							Set rsICFilters = Server.CreateObject("ADODB.Recordset")
		
							SQLICFilters = "SELECT prodSKU, prodDescription FROM IC_Product ORDER BY prodSKU"
							Set rsICFilters = cnnICFilters.Execute(SQLICFilters)
							
							If NOT rsICFilters.EOF Then
							
								Do While NOT rsICFilters.EOF
								
									Response.Write("<option value='" & rsICFilters("prodSKU") & "'>" & rsICFilters("prodSKU") & " - " & rsICFilters("prodDescription") & "</option>")
								
									rsICFilters.Movenext
								Loop
							
							End If
							
							set rsICFilters = nothing
							cnnICFilters.close
							set cnnICFilters = nothing
		
							%>	
						</select>
					</div>
				</div>		
					
				<div class="row modalrow">
	         	   	<div class="col-lg-4">Display Order</div>
		         	   	<div class="col-lg-8">
		         	   	<select class="form-control" id="selFilterdisplayOrder" name="selFilterdisplayOrder">		
			         	   	<option value="0">0</option>
			         	   	<%
								For x = 1 to 99
								
									Response.Write("<option value='" & x & "'>" & x & "</option>")
								
								Next									
							%>	
						</select>
					</div>
				</div>		
	         	<div class="row" style="margin-top:20px">
	         	   	<div class="col-lg-6">&nbsp;</div>
		         	<div class="col-lg-6 pull-right" style="margin-right: -50px;">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="button" class="btn btn-primary" id="AddFilterSave" name="AddFilterSave" value="Save"><i class="fa fa-floppy-o" aria-hidden="true"></i>&nbsp;Save New Filter</button>
					</div>
				</div>

			</div>
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- Edit Existing Filter Modal -->
<div class="modal fade" id="modalEditExistingFilter" tabindex="-1" role="dialog" aria-labelledby="modalEditExistingFilterLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<style>
				.modal-header {
				    padding: 15px;
				    border-bottom: 1px solid #e5e5e5;
				    min-height: 135px;
				}
		
				.title-right {
					position:relative;
					right:0;
					top:0;
					width:40%;
					color:#FF0000;
					display: inline-block;"
				}
				.title-left {
					position:relative;
					left:0;
					top:0;
					width:55%;
					display: inline-block;"			
				}		
				.modalrow {
					    border-bottom: 1px solid #ddd !important;	
					    padding-bottom:20px;	
					    padding-top:20px;		
			    }
			    .width25 {
					width:25%;
					display:inline;
				}

			    .width50 {
					width:50%;
					display:inline;
				}

			    .width75 {
					width:75%;
					display:inline;
				}
			
			</style>
			<div id="modalEditExistingFilterContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForEditFilterModal() in InsightFuncs_AjaxForServiceModals.asp -->				
			</div>
				
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


<!-- Delete Existing Filter Modal -->
<div class="modal fade" id="modalDeleteExistingFilter" tabindex="-1" role="dialog" aria-labelledby="modalDeleteExistingFilterLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<style>
				.modal-header {
				    padding: 15px;
				    border-bottom: 1px solid #e5e5e5;
				    min-height: 135px;
				}
		
				.title-right {
					position:relative;
					right:0;
					top:0;
					width:40%;
					color:#FF0000;
					display: inline-block;"
				}
				.title-left {
					position:relative;
					left:0;
					top:0;
					width:55%;
					display: inline-block;"			
				}		
				.modalrow {
					    border-bottom: 1px solid #ddd !important;	
					    padding-bottom:20px;	
					    padding-top:20px;		
			    }
			    .width25 {
					width:25%;
					display:inline;
				}

			    .width50 {
					width:50%;
					display:inline;
				}

			    .width75 {
					width:75%;
					display:inline;
				}
			
			</style>
			<div id="modalDeleteExistingFilterContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForDeleteFilterModal() in InsightFuncs_AjaxForServiceModals.asp -->				
			</div>
				
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->


