<div class="waitdiv d-none" style="position: fixed;z-index: 999999999; top: 0px; left: 0px; width: 100%; height:80%; background-color:transparent; text-align: center; padding-top: 20%; filter: alpha(opacity=0); opacity:0; "></div>
	<div id="waitdiv" class="waitdiv d-none small" style="padding-bottom: 90px;text-align: center; vertical-align:middle;padding-top:50px;background-color:#ebebeb;width:300px;height:100px;margin: 0 auto; top:40%; left:40%;position:absolute;-webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2); -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2); box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2); z-index:999999999;">
		<img src="/img/loading_gray.gif" alt="" /><br /><span id="waitmsg">Loading Filter Change Information.</span> <br />Please wait ...
</div>

<link href="/css/air-datepicker/air-datepicker.css" rel="stylesheet" type="text/css">
<script src="/js/air-datepicker/datepicker.min.js"></script>
<script src="/js/air-datepicker/i18n/datepicker.en.js"></script>
<!-- pencil Modal -->
<div class="modal modal-wide fade" id="modalEditCategoryNotes" tabindex="-1" role="dialog" aria-labelledby="modalEditCategoryNotesLabel">

	<style>
	.modal-header {
	    padding: 15px;
	    border-bottom: 1px solid #e5e5e5;
	    min-height: 35px !important;
	}
	</style>
	
	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

			<input type="hidden" name="txtCategoryID" id="txtCategoryID">
			<input type="hidden" name="txtCustIDToPass" id="txtCustIDToPass">
			    
			<div id="modalEditCategoryNotesContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForCategoryAnalysisByPeriodNotesModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
			</div>

				  
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>
	

		</div>
		<!-- eof modal content !-->
</div>
<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->



<!-- modal -->

	
<div class="modal fade" id="modalMemos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Memos</h4>
      </div>
      <div class="modal-body">
        Memos content goes here.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- eof modal -->






<!-- Equipment Modal -->
<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}
		
		.tile {
		  width: 6%;
		  display: inline-block;
		  box-sizing: border-box;
		  background: #fff;
		  padding-top: 10px;
		  padding-top: 10px;
		  padding-left: 5px;
		  color:#FFF;
		}
		
		.tile .title {
		  margin-top: 0px;
		}
		
		.tile.red {
		  background: #AC193D;
		  color:#FFF;
		}
		
		.tile.red:hover {
		  background: #7f132d;
		  color:#FFF;
		}
		
		.tile.blue {
		  background: #2672EC;
		  color:#FFF;
		}
		
		.tile.blue:hover {
		  background: #125acd;
		  color:#FFF;
		}
		
		.equip_qty{
			font-weight:bold;
			font-size:1.2em;
	
		}
		
	</style>
	
<div class="modal modal-xwide fade" id="modalEquipmentVPC" tabindex="-1" role="dialog" aria-labelledby="modalEquipmentVPCLabel">

	<div class="modal-dialog" role="document">
	
	
						
		<div class="modal-content">	
		
			<input type="hidden" name="txtCustIDToPass" id="txtCustIDToPass">
			<input type="hidden" name="txtLastClosedPeriodGP" id="txtLastClosedPeriodGP">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalEquipmentVPCTitle"><!-- Content generated by Sub GetTitleForEquipmentVPCModal() in InsightFuncs_AjaxForBizIntelModals.asp --></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
			
				<div id="PleaseWaitPanelModal">
				<br><br><strong>Analyzing Equipment for <%= CustName %>, please wait...</strong><br><br>
				<img src="<%= BaseURL %>img/loading.gif">
				</div>	
			
				<div id="modalCategoryVPCContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForEquipmentVPCModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->





<!-- modal -->
<div class="modal fade bs-example-modal-lg" id="modalServiceTickets" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Service Tickets</h4>
      </div>
      <div class="modal-body">
        Service Tickets content goes here.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- eof modal -->



<!-- modal -->
<div class="modal fade bs-example-modal-lg" id="modalXPage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">X Page</h4>
      </div>
      <div class="modal-body">
        X Page content goes here.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- eof modal -->


<!-- VPC Modal -->
<div class="modal modal-xwide fade" id="modalCategoryVPC" tabindex="-1" role="dialog" aria-labelledby="modalCategoryVPCLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
		
			<input type="hidden" name="txtCategoryID" id="txtCategoryID">
			<input type="hidden" name="txtCustIDToPass" id="txtCustIDToPass">
			<input type="hidden" name="txtPeriodSeqToPass" id="txtPeriodSeqToPass">
			<input type="hidden" name="txtVarianceBasisToPass" id="txtVarianceBasisToPass">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalCategoryVPCTitle"></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalCategoryVPCContent">
				<!-- Content for the modal will be generated and written here -->
				<!-- Content generated by Sub GetContentForCategoryVPCModal() in InsightFuncs_AjaxForBizIntelModals.asp -->
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close Window</button>
			</div>

		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- General Notes Group M Modal -->
<div class="modal fade" id="modalGeneralNotesGroupM" tabindex="-1" role="dialog" aria-labelledby="modalGeneralNotesGroupMLabel">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		.title-right {
			position:relative;
			right:0;
			top:0;
			width:40%;
			color:#FF0000;
			display: inline-block;
		}
		.title-left {
			position:relative;
			left:0;
			top:0;
			width:55%;
			display: inline-block;			
		}		
	
	</style>
			<input type="hidden" name="GNGMCustIDToPass" id="GNGMCustIDToPass">
			<input type="hidden" name="GNGMuserno" id="GNGMuserno">
			<input type="hidden" name="GNGMMSCMonth" id="GNGMMSCMonth">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalGeneralNotesGroupMTitle"><div class="title-left"><span id="GNGMcustname"></span></div><div class="title-right"><span id="GNGMvariance"></span></div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalGeneralNotesGroupMContent">
					<table class="table-condensed table-hover large-table">			
						<tbody>
							<tr>
								<td><input type="radio" name="groupm" value="no_action_necessary" checked> No action necessary at this time.</td><td><select id="GNGMReasons"><option value="selectreason">Select Reason</option></select></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm" value="remove_client"> Remove this client from the MCS program<br></td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm" value="change_mcs"> Change this client's MCS to:</td>
								<td>$&nbsp;<input type="text" class="" id="GNGMchange_mcs" size="17" value=""></td>
								<td>&nbsp;</td>
							</tr>							
							<tr>
								<td><input type="radio" name="groupm" value="change_lvf"> Change the maximum LVF for this client to :</td>
								<td>$&nbsp;<input type="text" class="" id="GNGMchange_lvf" size="17" value=""></td><td class="smaller-detail-line"><span>&nbsp;</span></td>
								<td>&nbsp;</td>
							</tr>														
							<tr>
								<td><input type="radio" name="groupm" value="send_invoice"> Send this client an invoice for the following amount:</td>
								<td>$&nbsp;<input type="text" class="" id="GNGMinvoice_amount" size="17" value=""></td><td class="smaller-detail-line-r"><span id="maxallowed">Max Allowed</span></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm"  value="notify_selected_sales_person"> Notify the selected <%= GetTerm("salesperson") %> to followup on the MCS shortage: </td>
								<td><select id="GNGMsalesperson">
									<option id="GNGMsp1" value=""><%= GetTerm("Primary Salesman") %></option>
									<option id="GNGMsp2" value=""><%= GetTerm("Secondary Salesman") %></option>
									</select>
								</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td><input type="radio" name="groupm" value="send_message_to_someone"> Send someone a message about this client.</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>														
							<tr class="hidemsg">
								<td colspan=2>Inclue the following message with the followup email:<br>
									<textarea id="GNGMMsg" name="GNGMMsg" rows="5" cols="70"></textarea>
								</td>			
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="GNGMSave" name="GNGMSave" value="Save">Save</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Add MCS Client Modal -->
<div class="modal fade" id="modalAddMCSClient" tabindex="-1" role="dialog" aria-labelledby="modalAddMCSClient">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	

<% ClientKeyForFileNames = MUV_READ("ClientKeyForFileNames") %>

<!---------------------------------------------------------------------------------------------------------->
<!----------THIS IS A CUSTOM STYLESHEET ADDED FOR THE AUTOCOMPLETE SEARCH FOR CATEGORY ANALYSIS ONLY-------->
<!-----------IT OVERRIDES THE STYLES THAT ARE STILL LOADED IN HEADER.ASP------------------------------------>

<!---------------------------------------------------------------------------------------------------------->
<link rel="stylesheet" href="http://dev.mdsinsight.com/js/easyautocomplete/EasyAutocomplete-1.4.0/easy-autocomplete-cat-analysis.css"> 

<!---------------------------------------------------------------------------------------------------------->
<!---------------------------------------------------------------------------------------------------------->
<!--
	js/easyautocomplete/EasyAutocomplete-1.4.0/easy-autocomplete.themes.css ALSO CONTAINS A CUSTOM STYLE
	SET CALLED "easy-autocomplete.eac-cat-analysis"
-->
<!---------------------------------------------------------------------------------------------------------->
<!---------------------------------------------------------------------------------------------------------->

<script type="text/javascript">

	var autocompleteJSONFileURLAccount = "/clientfiles/<%= ClientKeyForFileNames %>/autocomplete/customer_account_list_CSZ_<%= ClientKeyForFileNames %>.json";
	
$(document).ready(function(){

	var optionsAccount = {
	  url: autocompleteJSONFileURLAccount,
	  placeholder: "Search for a customer by name, account, city, state, zip",
	  getValue: "name",
	  list: {	
        onChooseEvent: function() {
        
            var custID = $("#txtCustID").getSelectedItemData().code;  
			$("#AddMCSClientCustNameToPass").val($("#txtCustID").getSelectedItemData().name.split(" --- ")[1])			
			$("#AddMCSClientCustIDToPass").val(custID);
			            		
            //window.location.href = "CatAnalByPeriod_SingleCustomer.asp?CID=" + custID + "&ZDC=0&VB=3Periods" + "&oon=" + oldornew;
			
            
    	},		  
	    match: {
	      enabled: true
		},
		maxNumberOfElements: 20		
	  },
	  theme: "cat-analysis"
	};
	$("#txtCustID").easyAutocomplete(optionsAccount);
	$('#LastChangedData').datepicker({
    position: 'right center', // Default position
	language: 'en',
	autoClose:true,
    onHide: function(inst){
        inst.update('position', 'right center'); // Update the position to the default again
    },
    onShow: function(inst, animationComplete){
        // Just before showing the datepicker
        if(!animationComplete){
            var iFits = false;
            // Loop through a few possible position and see which one fits
            $.each(['right center', 'right bottom', 'right top', 'top center', 'bottom center', 'left center', 'left top'], function (i, pos) {
                if (!iFits) {
                    inst.update('position', pos);
                    var fits = isElementInViewport(inst.$datepicker[0], "#modalEditCustomerFilter");
					
                    if (fits.all) {
                        iFits = true;
                    }
                }
            });
        }
    },

});
	
	
	
	///*********************************************
	
	
	
	$("#FrequencyTime").empty();
	for (j=1;j<366; j++) {
		$("#FrequencyTime").append( $('<option value="'+j+'">'+j+'</option>'));
	
	}
	$("#FrequencyTime :first").attr("selected", "selected");
	$("#qty").empty();
				for (j=1;j<2; j++) {
					$("#qty").append( $('<option value="'+j+'">'+j+'</option>'));
	
				}
	$("#qty :first").attr("selected", "selected");			
});
	

</script>
	<style>
		.modal-header {
		    padding: 15px;
		    border-bottom: 1px solid #e5e5e5;
		    min-height: 135px;
		}

		.easy-autocomplete.eac-round input{
			width: 100% !important;
		}
		.title-right {
			position:relative;
			right:0;
			top:0;
			width:40%;
			color:#FF0000;
			display: inline-block;
		}
		.title-left {
			position:relative;
			left:0;
			top:0;
			width:55%;
			display: inline-block;		
		}		
	
	</style>
				
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalAddMCSClientTitle"><div class="title-left"><span id="GNGMcustname"></span></div><div class="title-right"><span id="GNGMvariance"></span></div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalAddMCSClientContent">
					<table class="table-condensed table-hover large-table">			
						<tbody>				
							<tr>
								<td colspan="2">
									<!-- select Client !-->
										<input id="txtCustID" name="txtCustID">
										<input type="hidden" id="AddMCSClientCustIDToPass" name="txtCustIDToPass" value="" >
										<input type="hidden" id="AddMCSClientCustNameToPass" name="txtCustNameToPass" value="" >
										<i id="searchIcon" class="fa fa-search fa-2x"></i>
									<!-- eof select Client !-->		
								</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="AddMCSClientSave" name="AddMCSClientSave" value="Continue">Continue</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->

<!-- Add MCS Client Modal Setp 2 -->
<style>
		.error {
		  background: #AC193D;
		  color:#FFF;
		}
		.modal-xl {
			width:80%;
			max-width: 1140px;
			
		}
		.modal-xl .modal-body  {
			height:calc(70vh);
			overflow-y:auto;
		
		}
		tr.for-edit {cursor:pointer;}
		tr.for-edit.selected, tr.for-edit.selected:hover {
			background-color:#cacaca;
		}
		tr.for-edit.selected {
			
			font-weight:bold;
		}
		tr.for-edit.selected.editable {
			
			font-weight:normal;
		}
		.filter-program,.equipment-list {
			overflow-y:auto;
		}
		</style>
		
<div class="modal fade" id="modalEditCustomerFilter" tabindex="-1" role="dialog" aria-labelledby="modalEditCustomerFilterLabel">

	<div class="modal-dialog modal-xl" role="document">
						
		<div class="modal-content">	
		
			
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalEditCustomerFilterTitle"><div class="title-left"><span id="mode">Add</span> Client <span id="EditCustomerFiltercustid"></span> - <span id="EditCustomerFiltercustname"></span> To Filter Program </div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<input type="hidden" name="EditCustomerFilterCustIDToPass" id="EditCustomerFilterCustIDToPass">
				<div class="filter-program">
					<table class="table table-hover filterList">
					<thead>
						<tr>
							<th style="width:250px;">Filter ID</th>
							<th>Filter Location</th>
							<th style="width:100px;">Qty</th>
							<th style="width:100px;">Frequency Type</th>
							<th style="width:100px;">Frequency Time</th>
							<th style="width:100px;">Price</th>
							<th style="width:150px;">Last Changed</th>	
						</tr> 
					</thead>
					<tbody>
						<!--#include file="newline_ajax.asp"-->
					</tbody>
				</table>
				
			
				</div>
				<div class="equipment-list">
					
				</div>
				
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" onclick="javascript:toAddLine();"><span class="glyphicon glyphicon-plus"></span>&nbsp;Add Another Line</button>
				
				<button type="button" class="btn btn-default" onclick="javascript:deleteRow();"><span class="glyphicon glyphicon glyphicon-trash"></span>&nbsp;Remove Line</button>
				<span>&nbsp;&nbsp;&nbsp;</span>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-primary" OnClick="javascript: addCustomerToDB();">Save and Close Window</button>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog">

	<div class="modal-dialog" role="document">
						
		<div class="modal-content">	
		
			
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title"></h4>
			</div>
			
			<div class="modal-body">
				
				
			
			</div>
			<div class="modal-footer">
				
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-primary" OnClick="">Yes, delete</button>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>

<script language="Javascript">
var values=[];
var currentCustomerID="";
	///*************************** datepicker area
	
	// A function to check wether the element fits inside the viewport:
function isElementInViewport(el, viewportEl) {
		var element=$(viewportEl);
		var viewportLeft=parseInt($("#modalEditCustomerFilter").find(".modal-dialog").css("margin-left"));
		var viewportRight=viewportLeft+parseInt($("#modalEditCustomerFilter").find(".modal-dialog").width());
		var viewportTop=parseInt($("#modalEditCustomerFilter").find(".modal-dialog").css("margin-top"));
		var viewportBottom=viewportLeft+parseInt($("#modalEditCustomerFilter").find(".modal-dialog").height());
		
        var rect = el.getBoundingClientRect();
		
        var fitsLeft = (rect.left >= 0 && rect.left >=viewportLeft );
        var fitsTop = (rect.top >= 0 && rect.top <= element.position().viewportTop);
        var fitsRight = (rect.right >= 0 && rect.right <= viewportRight);
        var fitsBottom = (rect.bottom >= 0 && rect.bottom <= viewportBottom);
        return {
            top: fitsTop,
            left: fitsLeft,
            right: fitsRight,
            bottom: fitsBottom,
            all: (fitsLeft && fitsTop && fitsRight && fitsBottom)
        };
    }

function toExclude(obj) {
	
	currentCustomerID=$(obj).attr("data-id");
	$("#confirmDelete .modal-title").html("Please confirm delete");
	$("#confirmDelete .modal-body").html("Are you sure to delete this customer from database and remove from Filter Program?");
	$("#confirmDelete .modal-footer .btn.btn-primary").attr("onclick","javascript:doDeleteFromProgram();");
	$("#confirmDelete").modal("show");
}
function doDeleteFromProgram() {
	if (currentCustomerID.length>0) {
	
		$.ajax({
			type:"GET",
			url: "deletecustomer.asp",
			cache: false,
			data: "customerID="+currentCustomerID,
			success: function(response) {
			
				location.reload();
			},
			error:function(response) {
			
			},
			complete:function(response) {
			
			}
		});
	
	}
}
function callEdit(obj) {
	var objData=$(obj).parent("tr");
	doEdit(objData);


}
function doEdit(obj) {
		$.ajax({
			type:"GET",
			url: "editFilterDataList.asp",
			cache: false,
			data: "CustomerID="+$(obj).attr("data-id"),
			success: function(response) {
				$("#modalEditCustomerFilter #mode").html("Edit");
				$("#modalEditCustomerFilter .modal-body").html(response);
				$("#modalEditCustomerFilter .modal-footer .btn.btn-primary").html("Save & Close Window");
				
				$("#modalEditCustomerFilter").modal("show");
			},
			error: function (response) {
			
			
			},
			complete: function() {
			$("#modalEditCustomerFilter .modal-title #EditCustomerFiltercustid").html($("#EditCustomerFilterCustIDToPass").val());
				$("#modalEditCustomerFilter .modal-title #EditCustomerFiltercustname").html($("#EditCustomerFilterCustName").val());
			$("#modalEditCustomerFilter .filter-program").height($("#modalEditCustomerFilter .modal-body").height()*0.4);
				var divHeight=$("#modalEditCustomerFilter .modal-body").height()*0.6-72;
				console.log(divHeight);
				$("#modalEditCustomerFilter .equipment-list").height(divHeight);
			}
			
		});
}
function createNewFilterTicket(obj) {
	passedCustID = $(obj).attr("data-custid");
	if (passedCustID.length>0) {
	
		if ($("[data-child-value='"+passedCustID+"'] td[ticket-data]").length==0 || ($("[data-child-value='"+passedCustID+"'] td[ticket-data]").length>=0 && $("[data-child-value='"+passedCustID+"'] td[ticket-data]").length!=$("[data-child-value='"+passedCustID+"']").length)) {
			if ($("[data-child-value='"+passedCustID+"'] td[ticket-data]").length==0 ) textMessage="This will create a filter change ticket for customer " + passedCustID + " for ALL filters. Would you like to continue?";
			else textMessage=" A filter change ticket already exists for this customer. Do you want to add the remaining filters to the ticket?";
			swal({
				title: "Confirm Ticket Creation",
				text: textMessage,
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Yes, continue!",
				closeOnConfirm: true
			}, function(isConfirm){
				if (isConfirm) {
					
					textMessage=$(".waitdiv #waitmsg").html();
					$("#waitmsg").html("Creating filter change ticket...");
					$(".waitdiv").removeClass("d-none");
					$.ajax({
						type:"POST",
						url: "createTicket_submit.asp",
						cache: false,
						data: "CustID="+$(obj).attr("data-custid"),
						success: function(response) {
							result=JSON.parse(response);
						
							$(".waitdiv").addClass("d-none");
							$("#waitmsg").html(result.message);
							if (result.result == "0") {
								$("tr[data-child-value='"+passedCustID+"']").each(function() {
									if ($(this).find("td").eq(12).html().length==0) {
										$(this).find("td").eq(12).html(result.ticketNumber);
										$(this).find("td").eq(12).attr("ticket-data",result.ticketNumber);
									}
								});								
								swal("Filter Ticket Created");
							}
							else {
								swal("An error was encountered while creating the ticket for this filter change. The error is " + response);
							//swal(response);
							}
						},
						error: function (response) {
							$("#waitmsg").html(textMessage);
							$(".waitdiv").addClass("d-none");
						},
						complete: function() {
							$("#waitmsg").html(textMessage);
							$(".waitdiv").addClass("d-none");
						}
					});
		
				}
			});
		}
		if ($("[data-child-value='"+passedCustID+"'] td[ticket-data]").length>=0 && $("[data-child-value='"+passedCustID+"'] td[ticket-data]").length==$("[data-child-value='"+passedCustID+"']").length) {
			swal("All the filters for this customer are already on an open filter change ticket.");
		
		
		}
	}
	else {
	
		passedCustID = $(obj).closest("tr").find("td").eq(0).html();
		passedFilterID=$(obj).attr("data-filterintrecid");
		if ($(obj).closest("tr").find("td[ticket-data]").length>0) {
			swal("This filter is already on an open filter change ticket.");
		}
		else {
			textMessage="This will create a filter change ticket for this filter only. If the customer has more than one filter on file, they will not be included as part of this ticket. If you wish to create a ticket for all filters, you may do so from the By Customer tab, or click Continue to proceed.";
			swal({
				title: "Confirm Ticket Creation",
				text: textMessage,
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Yes, continue!",
				closeOnConfirm: true
			}, function(isConfirm){
				if (isConfirm) {
					
					textMessage=$(".waitdiv #waitmsg").html();
					$("#waitmsg").html("Creating filter change ticket...");
					$(".waitdiv").removeClass("d-none");
					$.ajax({
						type:"POST",
						url: "createTicket_submit.asp",
						cache: false,
						data: "FilterIntRecID="+$(obj).attr("data-filterintrecid")+"&CustID="+passedCustID,
						success: function(response) {
							result=JSON.parse(response);
						
							$(".waitdiv").addClass("d-none");
							$("#waitmsg").html(result.message);
							if (result.result == "0") {
								
								$(obj).closest("tr").find("td").eq(14).html(result.ticketNumber);
								$(obj).closest("tr").find("td").eq(14).attr("ticket-data",result.ticketNumber);
								swal("Filter Ticket Created");
							}
							else {
								swal("An error was encountered while creating the ticket for this filter change. The error is " + response);
							//swal(response);
							}
						},
						error: function (response) {
							$("#waitmsg").html(textMessage);
							$(".waitdiv").addClass("d-none");
						},
						complete: function() {
							$("#waitmsg").html(textMessage);
							$(".waitdiv").addClass("d-none");
						}
					});
					
				}
			});
		
		}
	}
}

function createNewFilterTicket_old(obj) {

		passedCustID = $(obj).attr("data-custid");
		passedFilterIntRecID = $(obj).attr("data-filterintrecid");
		var textMessage="";
		
		if ($("#ViewMode li.active a").attr("href")=="#detailed") textMessage="This will create a filter change ticket for this filter only. Do you want to continue?";
		else textMessage="This will create a filter change ticket for customer " + passedCustID + " for ALL filters. Would you like to continue? ";
		//alert("passedCustID : " + passedCustID);
		//alert("passedFilterIntRecID: " + passedFilterIntRecID);
		swal({
        title: "Confirm Ticket Creation",
        text: textMessage,
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes, continue!",
        closeOnConfirm: true
    }, function(isConfirm){
        if (isConfirm) {
		textMessage=$(".waitdiv #waitmsg").html();
		$("#waitmsg").html("Creating filter change ticket...");
		$(".waitdiv").removeClass("d-none");
		$.ajax({
			type:"POST",
			url: "createTicket_submit.asp",
			cache: false,
			data: "FilterIntRecID="+$(obj).attr("data-filterintrecid")+"&CustID="+$(obj).attr("data-custid"),
			success: function(response) {
			$(".waitdiv").addClass("d-none");
			$("#waitmsg").html(textMessage);
				if (response == "success") {
					swal("Filter Ticket Created");
				}
				else {
					swal("An error was encountered while creating the ticket for this filter change. The error is " + response);
					//swal(response);
				}
			},
			error: function (response) {
			$("#waitmsg").html(textMessage);
			$(".waitdiv").addClass("d-none");
			},
			complete: function() {
			$("#waitmsg").html(textMessage);
			$(".waitdiv").addClass("d-none");
			}
		});
		}
    });
	
		
}

function addCustomerToDB() {

setToReadLine();
var selectedDate="";
$("#modalEditCustomerFilter tr.for-edit").each(function() {
	var rowdata="";
	$(this).find("td").each(function() {
		
		if (rowdata.length>0) rowdata+=",";
		rowdata+='"'+$(this).attr("data-id")+'":"'+$(this).attr("data-value")+'"';
	});
	if (selectedDate.length>0) selectedDate+=",";
	selectedDate+='{'+rowdata+'}';
});
selectedDate='{"customerID":"'+$("#EditCustomerFilterCustIDToPass").val()+'","datatodb":['+selectedDate+']}';


$.ajax({
	type:"POST",
	url: "addcustomer.asp",
	cache: false,
	data: { data: selectedDate},
	success: function(response) {
		location.reload();
	},
	error:function(response) {
	
	},
	complete:function(response) {
	
	}
	});
}






function setToReadLine() {
	if ($("#modalEditCustomerFilter tr.for-edit.editable").length>0)  {
		var myDatepicker =$('#LastChangedData').datepicker().data('datepicker');
			
			$("#modalEditCustomerFilter tr.for-edit.editable td").each(function() {
				var valueData=$(this).find(".form-control").val();
				$(this).attr("data-value",valueData);
				$(this).attr("data-id",$(this).find(".form-control").attr("id"));
				if ($(this).find(".form-control").prop('nodeName')=="SELECT") valueData=$(this).find(".form-control :selected").text();
				$(this).html(valueData);
				
			});
			myDatepicker.destroy();
		$("#modalEditCustomerFilter tr.for-edit.editable").removeClass("editable");	
	}
}

function selectRow(obj) {
	if (!$(obj).hasClass("selected")) {
	setToReadLine();
	$("#modalEditCustomerFilter tr.for-edit").removeClass("selected").removeClass("editable");
	$(obj).addClass("selected");
	editLine();
	}
}
function deleteRow() {
	if ($("#modalEditCustomerFilter tr.for-edit.selected").length>0) {
		$("#modalEditCustomerFilter tr.for-edit.selected").remove();
	}
}
function editLine() {
	if ($("#modalEditCustomerFilter tr.for-edit.editable").length===0 && $("#modalEditCustomerFilter tr.for-edit.selected").length>0) {
	
	$.ajax({
			type:"GET",
			url: "newline_ajax.asp",
			cache: false,
			
			success: function(response)
			 {
				values=[];
				$("#modalEditCustomerFilter tr.for-edit.selected td").each(function() {
					values.push($(this).attr("data-value"));
				});
				
				$( "#modalEditCustomerFilter tr.for-edit.selected").replaceWith(response)
               	
				$("#FrequencyTime").empty();
				for (j=1;j<366; j++) {
					$("#FrequencyTime").append( $('<option value="'+j+'">'+j+'</option>'));
	
				}
				$("#qty").empty();
				for (j=1;j<2; j++) {
					$("#qty").append( $('<option value="'+j+'">'+j+'</option>'));
	
				}
				for (j=0;j<values.length;j++) {
					$($("#modalEditCustomerFilter tr.for-edit.editable td")[j]).find(".form-control").val(values[j]);
					$($("#modalEditCustomerFilter tr.for-edit.editable td")[j]).attr("data-value",values[j]);
				}
				
				$('#LastChangedData').datepicker({
					position: 'right center', // Default position
					language: 'en',
					autoClose:true,
					
					onHide: function(inst){
						inst.update('position', 'right center'); // Update the position to the default again
					},
					onShow: function(inst, animationComplete){
						// Just before showing the datepicker
						if(!animationComplete){
							var iFits = false;
							// Loop through a few possible position and see which one fits
							$.each(['right center', 'right bottom', 'right top', 'top center', 'bottom center', 'left center', 'left top'], function (i, pos) {
								if (!iFits) {
									inst.update('position', pos);
									var fits = isElementInViewport(inst.$datepicker[0], "#modalEditCustomerFilter");
									console.log(fits);
									if (fits.all) {
										iFits = true;
									}
								}
							});
						}
					},

				});				 
				var datepicker=$('#LastChangedData').datepicker().data('datepicker');
				if ($("#modalEditCustomerFilter tr.for-edit.editable td:last").attr("data-value").length>0) datepicker.selectDate(stringToDate($("#modalEditCustomerFilter tr.for-edit.editable td:last").attr("data-value"),"MM/dd/yyyy","/"));
             },
             failure: function(response)
			 {
			  	
             }
			});
	
	}
}
	function toAddLine() {
		if ($("#modalEditCustomerFilter tr.for-edit.editable").length>0)  {
			var myDatepicker =$('#LastChangedData').datepicker().data('datepicker');
			
			$("#modalEditCustomerFilter tr.for-edit.editable td").each(function() {
				var valueData=$(this).find(".form-control").val();
				$(this).attr("data-value",valueData);
				if ($(this).find(".form-control").prop('nodeName')=="SELECT") valueData=$(this).find(".form-control :selected").text();
				$(this).html(valueData);
				
			});
			myDatepicker.destroy();
			
			}
			$.ajax({
			type:"GET",
			url: "newline_ajax.asp",
			cache: false,
			
			success: function(response)
			 {
				$("#modalEditCustomerFilter tr.for-edit").removeClass("selected").removeClass("editable");
               	$("#modalEditCustomerFilter .filterList").append(response); 
				$("#FrequencyTime").empty();
				for (j=1;j<366; j++) {
					$("#FrequencyTime").append( $('<option value="'+j+'">'+j+'</option>'));
	
				}
				$("#qty").empty();
				for (j=1;j<2; j++) {
					$("#qty").append( $('<option value="'+j+'">'+j+'</option>'));
	
				}
	$("#FrequencyTime :first").attr("selected", "selected");
				$('#LastChangedData').datepicker({
					position: 'right center', // Default position
					language: 'en',
					autoClose:true,
					onHide: function(inst){
						inst.update('position', 'right center'); // Update the position to the default again
					},
					onShow: function(inst, animationComplete){
						// Just before showing the datepicker
						if(!animationComplete){
							var iFits = false;
							// Loop through a few possible position and see which one fits
							$.each(['right center', 'right bottom', 'right top', 'top center', 'bottom center', 'left center', 'left top'], function (i, pos) {
								if (!iFits) {
									inst.update('position', pos);
									var fits = isElementInViewport(inst.$datepicker[0], "#modalEditCustomerFilter");
									console.log(fits);
									if (fits.all) {
										iFits = true;
									}
								}
							});
						}
					},

				});				 
				 
             },
             failure: function(response)
			 {
			  	
             }
			});
		
		
	
	}
	function listbox_addSelectUser() {
	
		var src = document.getElementById("lstSelectUserIDs");
		var dest = document.getElementById("lstSelectedUserIDs");
	
		for(var count=0; count < src.options.length; count++) {
	
			if(src.options[count].selected == true) {
					var option = src.options[count];
	
					var newOption = document.createElement("option");
					newOption.value = option.value;
					newOption.text = option.text;
					newOption.selected = true;
					try {
							 dest.add(newOption, null); //Standard
							 src.remove(count, null);
					 }catch(error) {
							 dest.add(newOption); // IE only
							 src.remove(count);
					 }
					count--;
			}
		}
	}	

	function listbox_removeSelectUser() {
	
		//var src = document.getElementById("lstSelectUserIDs");
		//var dest = document.getElementById("lstSelectedUserIDs");

		var dest = document.getElementById("lstSelectUserIDs");
		var src = document.getElementById("lstSelectedUserIDs");
	
		for(var count=0; count < src.options.length; count++) {
	
			if(src.options[count].selected == true) {
					var option = src.options[count];
	
					var newOption = document.createElement("option");
					newOption.value = option.value;
					newOption.text = option.text;
					newOption.selected = true;
					try {
							 dest.add(newOption, null); //Standard
							 src.remove(count, null);
					 }catch(error) {
							 dest.add(newOption); // IE only
							 src.remove(count);

					 }
					count--;
			}
		}
	}
	function stringToDate(_date,_format,_delimiter)
{
            var formatLowerCase=_format.toLowerCase();
            var formatItems=formatLowerCase.split(_delimiter);
            var dateItems=_date.split(_delimiter);
            var monthIndex=formatItems.indexOf("mm");
            var dayIndex=formatItems.indexOf("dd");
            var yearIndex=formatItems.indexOf("yyyy");
            var month=parseInt(dateItems[monthIndex]);
            month-=1;
            var formatedDate = new Date(dateItems[yearIndex],month,dateItems[dayIndex]);
            return formatedDate;
}
</script>			
			
<style>
	.keepcenter {
		text-align: center;
	}
</style>

<!-- eof modal !-->	

<!-- Select User Modal -->
<div class="modal fade" id="modalSelectUser" tabindex="-1" role="dialog" aria-labelledby="modalSelectUserLabel">

	<div class="modal-dialog" role="document">

		<div class="modal-content">	

			<input type="hidden" name="SUCustIDToPass" id="SUCustIDToPass">
			<input type="hidden" name="SUParamsFromParent" id="SUParamsFromParent">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalSelectUserTitle"><div class="title-left"><span id="SUcustname"></span></div><div class="title-right"><span id="SUvariance"></span></div></h4>
			</div>
			
			<div class="modal-body modalResponsiveTable">
				<div id="modalSelectUserContent">
					<table class="table-condensed table-hover large-table table-width">			
						<tbody>
							<tr>
								<td colspan="3"><strong>Send this message to the following people</strong></td>
							</tr>
							<tr>
								<td colspan="3">Master User List</td>
							</tr>
							<tr>
								<td>
								<select multiple class="form-control multi-select" id="lstSelectUserIDs" name="lstSelectUserIDs" style="width: 200px; height: 300px;">
									<option>Select User</option>
								</select>
								</td>
								<td class="keepcenter"> 
									<a href="javascript:void(0)" onclick="javascript:listbox_addSelectUser()"><button type="button" class="btn btn-success" style="margin-bottom:10px;margin-top:40px;">Add User <i class="fa fa-arrow-right" aria-hidden="true"></i></button></a>
									<BR>
									<a href="javascript:void(0)" onclick="javascript:listbox_removeSelectUser()"><button type="button" class="btn btn-danger"><i class="fa fa-arrow-left" aria-hidden="true"></i> Remove User </button></a>
								</td>
								<td>
								<select multiple class="form-control multi-select" id="lstSelectedUserIDs" name="lstSelectedUserIDs"  style="width: 200px; height: 300px;">
								
								</select>
								</td>
							</tr>							
							<tr>
								<td colspan="3"><strong>Please enter your message in the box below</strong><br>
									<textarea id="SUMsg" name="SUMsg" rows="5" cols="70"></textarea>
								</td>			
							</tr>
							<tr>								
								<td colspan="3" class="keepcenter">
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary" id="SUSave" name="SUSave" value="Save">Save</button>
								</td>
							</tr>							
						</tbody>
					</table>					
				</div>
			</div>
			
		</div>
		<!-- eof modal content !-->
	</div>
	<!-- eof modal dialog !-->
</div>
<!-- eof modal !-->