<%

If vendorState = "AA" Then Response.Write("<option selected value='AA'>" & "Armed Forces Americas" & "</option>") Else Response.Write("<option value='AA'>" & "Armed Forces Americas" & "</option>")
If vendorState = "AE" Then Response.Write("<option selected value='AE'>" & "Armed Forces Europe, Middle East, & Canada" & "</option>") Else Response.Write("<option value='AE'>" & "Armed Forces Europe, Middle East, & Canada" & "</option>")
If vendorState = "AK" Then Response.Write("<option selected value='AK'>" & "Alaska" & "</option>") Else Response.Write("<option value='AK'>" & "Alaska" & "</option>") 
If vendorState = "AL" Then Response.Write("<option selected value='AL'>" & "Alabama" & "</option>") Else Response.Write("<option value='AL'>" & "Alabama" & "</option>") 
If vendorState = "AP" Then Response.Write("<option selected value='AP'>" & "Armed Forces Pacific" & "</option>") Else Response.Write("<option value='AP'>" & "Armed Forces Pacific" & "</option>") 
If vendorState = "AR" Then Response.Write("<option selected value='AR'>" & "Arkansas" & "</option>") Else Response.Write("<option value='AR'>" & "Arkansas" & "</option>") 
If vendorState = "AS" Then Response.Write("<option selected value='AS'>" & "American Samoa" & "</option>") Else Response.Write("<option value='AS'>" & "American Samoa" & "</option>")
If vendorState = "AZ" Then Response.Write("<option selected value='AZ'>" & "Arizona" & "</option>") Else Response.Write("<option value='AZ'>" & "Arizona" & "</option>")
If vendorState = "CA" Then Response.Write("<option selected value='CA'>" & "California" & "</option>") Else Response.Write("<option value='CA'>" & "California" & "</option>")
If vendorState = "CO" Then Response.Write("<option selected value='CO'>" & "Colorado" & "</option>") Else Response.Write("<option value='CO'>" & "Colorado" & "</option>")
If vendorState = "CT" Then Response.Write("<option selected value='CT'>" & "Connecticut" & "</option>") Else Response.Write("<option value='CT'>" & "Connecticut" & "</option>")
If vendorState = "DC" Then Response.Write("<option selected value='DC'>" & "District of Columbia" & "</option>") Else Response.Write("<option value='DC'>" & "District of Columbia" & "</option>")
If vendorState = "DE" Then Response.Write("<option selected value='DE'>" & "Delaware" & "</option>") Else Response.Write("<option value='DE'>" & "Delaware" & "</option>") 
If vendorState = "FL" Then Response.Write("<option selected value='FL'>" & "Florida" & "</option>") Else Response.Write("<option value='FL'>" & "Florida" & "</option>")
If vendorState = "FM" Then Response.Write("<option selected value='FM'>" & "Federated States of Micronesia" & "</option>") Else Response.Write("<option value='FM'>" & "Federated States of Micronesia" & "</option>")
If vendorState = "GA" Then Response.Write("<option selected value='GA'>" & "Georgia" & "</option>") Else Response.Write("<option value='GA'>" & "Georgia" & "</option>")
If vendorState = "GU" Then Response.Write("<option selected value='GU'>" & "Guam" & "</option>") Else Response.Write("<option value='GU'>" & "Guam" & "</option>") 
If vendorState = "HI" Then Response.Write("<option selected value='HI'>" & "Hawaii" & "</option>") Else Response.Write("<option value='HI'>" & "Hawaii" & "</option>")
If vendorState = "IA" Then Response.Write("<option selected value='IA'>" & "Iowa" & "</option>") Else Response.Write("<option value='IA'>" & "Iowa" & "</option>") 
If vendorState = "ID" Then Response.Write("<option selected value='ID'>" & "Idaho" & "</option>") Else Response.Write("<option value='ID'>" & "Idaho" & "</option>") 
If vendorState = "IL" Then Response.Write("<option selected value='IL'>" & "Illinois" & "</option>") Else Response.Write("<option value='IL'>" & "Illinois" & "</option>") 
If vendorState = "IN" Then Response.Write("<option selected value='IN'>" & "Indiana" & "</option>") Else Response.Write("<option value='IN'>" & "Indiana" & "</option>")
If vendorState = "KS" Then Response.Write("<option selected value='KS'>" & "Kansas" & "</option>") Else Response.Write("<option value='KS'>" & "Kansas" & "</option>") 
If vendorState = "KY" Then Response.Write("<option selected value='KY'>" & "Kentucky" & "</option>") Else Response.Write("<option value='KY'>" & "Kentucky" & "</option>") 
If vendorState = "LA" Then Response.Write("<option selected value='LA'>" & "Louisiana" & "</option>") Else Response.Write("<option value='LA'>" & "Louisiana" & "</option>") 
If vendorState = "MA" Then Response.Write("<option selected value='MA'>" & "Massachusetts" & "</option>") Else Response.Write("<option value='MA'>" & "Massachusetts" & "</option>") 
If vendorState = "MD" Then Response.Write("<option selected value='MD'>" & "Maryland" & "</option>") Else Response.Write("<option value='MD'>" & "Maryland" & "</option>") 
If vendorState = "ME" Then Response.Write("<option selected value='ME'>" & "Maine" & "</option>") Else Response.Write("<option value='ME'>" & "Maine" & "</option>")
If vendorState = "MH" Then Response.Write("<option selected value='ME'>" & "Marshall Islands" & "</option>") Else Response.Write("<option value='ME'>" & "Marshall Islands" & "</option>") 
If vendorState = "MI" Then Response.Write("<option selected value='MI'>" & "Michigan" & "</option>") Else Response.Write("<option value='MI'>" & "Michigan" & "</option>") 
If vendorState = "MN" Then Response.Write("<option selected value='MN'>" & "Minnesota" & "</option>") Else Response.Write("<option value='MN'>" & "Minnesota" & "</option>") 
If vendorState = "MO" Then Response.Write("<option selected value='MO'>" & "Missouri" & "</option>") Else Response.Write("<option value='MO'>" & "Missouri" & "</option>") 
If vendorState = "MP" Then Response.Write("<option selected value='MP'>" & "Northern Mariana Islands" & "</option>") Else Response.Write("<option value='MP'>" & "Northern Mariana Islands" & "</option>")
If vendorState = "MS" Then Response.Write("<option selected value='MS'>" & "Mississippi" & "</option>") Else Response.Write("<option value='MS'>" & "Mississippi" & "</option>") 
If vendorState = "MT" Then Response.Write("<option selected value='MT'>" & "Montana" & "</option>") Else Response.Write("<option value='MT'>" & "Montana" & "</option>") 
If vendorState = "NC" Then Response.Write("<option selected value='NC'>" & "North Carolina" & "</option>") Else Response.Write("<option value='NC'>" & "North Carolina" & "</option>") 
If vendorState = "ND" Then Response.Write("<option selected value='ND'>" & "North Dakota" & "</option>") Else Response.Write("<option value='ND'>" & "North Dakota" & "</option>") 
If vendorState = "NE" Then Response.Write("<option selected value='NE'>" & "Nebraska" & "</option>") Else Response.Write("<option value='NE'>" & "Nebraska" & "</option>") 
If vendorState = "NH" Then Response.Write("<option selected value='NH'>" & "New Hampshire" & "</option>") Else Response.Write("<option value='NH'>" & "New Hampshire" & "</option>") 
If vendorState = "NJ" Then Response.Write("<option selected value='NJ'>" & "New Jersey" & "</option>") Else Response.Write("<option value='NJ'>" & "New Jersey" & "</option>") 
If vendorState = "NY" Then Response.Write("<option selected value='NY'>" & "New York" & "</option>") Else Response.Write("<option value='NY'>" & "New York" & "</option>")
If vendorState = "NM" Then Response.Write("<option selected value='NM'>" & "New Mexico" & "</option>") Else Response.Write("<option value='NM'>" & "New Mexico" & "</option>") 
If vendorState = "NV" Then Response.Write("<option selected value='NV'>" & "Nevada" & "</option>") Else Response.Write("<option value='NV'>" & "Nevada" & "</option>") 
If vendorState = "OH" Then Response.Write("<option selected value='OH'>" & "Ohio" & "</option>") Else Response.Write("<option value='OH'>" & "Ohio" & "</option>") 
If vendorState = "OK" Then Response.Write("<option selected value='OK'>" & "Oklahoma" & "</option>") Else Response.Write("<option value='OK'>" & "Oklahoma" & "</option>") 
If vendorState = "OR" Then Response.Write("<option selected value='OR'>" & "Oregon" & "</option>") Else Response.Write("<option value='OR'>" & "Oregon" & "</option>") 
If vendorState = "PA" Then Response.Write("<option selected value='PA'>" & "Pennsylvania" & "</option>") Else Response.Write("<option value='PA'>" & "Pennsylvania" & "</option>") 
If vendorState = "PR" Then Response.Write("<option selected value='PR'>" & "Puerto Rico" & "</option>") Else Response.Write("<option value='PR'>" & "Puerto Rico" & "</option>") 
If vendorState = "PW" Then Response.Write("<option selected value='PW'>" & "Palau" & "</option>") Else Response.Write("<option value='PW'>" & "Palau" & "</option>") 
If vendorState = "RI" Then Response.Write("<option selected value='RI'>" & "Rhode Island" & "</option>") Else Response.Write("<option value='RI'>" & "Rhode Island" & "</option>") 
If vendorState = "SC" Then Response.Write("<option selected value='SC'>" & "South Carolina" & "</option>") Else Response.Write("<option value='SC'>" & "South Carolina" & "</option>") 
If vendorState = "SD" Then Response.Write("<option selected value='SD'>" & "South Dakota" & "</option>") Else Response.Write("<option value='SD'>" & "South Dakota" & "</option>") 
If vendorState = "TN" Then Response.Write("<option selected value='TN'>" & "Tennessee" & "</option>") Else Response.Write("<option value='TN'>" & "Tennessee" & "</option>") 
If vendorState = "TX" Then Response.Write("<option selected value='TX'>" & "Texas" & "</option>") Else Response.Write("<option value='TX'>" & "Texas" & "</option>")
If vendorState = "UT" Then Response.Write("<option selected value='UT'>" & "Utah" & "</option>") Else Response.Write("<option value='UT'>" & "Utah" & "</option>") 
If vendorState = "VA" Then Response.Write("<option selected value='VA'>" & "Virginia" & "</option>") Else Response.Write("<option value='VA'>" & "Virginia" & "</option>") 
If vendorState = "VI" Then Response.Write("<option selected value='VI'>" & "Virgin Islands" & "</option>") Else Response.Write("<option value='VI'>" & "Virgin Islands" & "</option>") 
If vendorState = "VT" Then Response.Write("<option selected value='VT'>" & "Vermont" & "</option>") Else Response.Write("<option value='VT'>" & "Vermont" & "</option>") 
If vendorState = "WA" Then Response.Write("<option selected value='WA'>" & "Washington" & "</option>") Else Response.Write("<option value='WA'>" & "Washington" & "</option>") 
If vendorState = "WV" Then Response.Write("<option selected value='WV'>" & "West Virginia" & "</option>") Else Response.Write("<option value='WV'>" & "West Virginia" & "</option>") 
If vendorState = "WI" Then Response.Write("<option selected value='WI'>" & "Wisconsin" & "</option>") Else Response.Write("<option value='WI'>" & "Wisconsin" & "</option>")
If vendorState = "WY" Then Response.Write("<option selected value='WY'>" & "Wyoming" & "</option>") Else Response.Write("<option value='WY'>" & "Wyoming" & "</option>") 
If vendorState = "AB" Then Response.Write("<option selected value='AB'>" & "Alberta" & "</option>") Else Response.Write("<option value='AB'>" & "Alberta" & "</option>") 
If vendorState = "BC" Then Response.Write("<option selected value='BC'>" & "British Columbia" & "</option>") Else Response.Write("<option value='BC'>" & "British Columbia" & "</option>") 
If vendorState = "MB" Then Response.Write("<option selected value='MB'>" & "Manitoba" & "</option>") Else Response.Write("<option value='MB'>" & "Manitoba" & "</option>") 
If vendorState = "NB" Then Response.Write("<option selected value='NB'>" & "New Brunswick" & "</option>") Else Response.Write("<option value='NB'>" & "New Brunswick" & "</option>") 
If vendorState = "NL" Then Response.Write("<option selected value='NL'>" & "Newfoundland" & "</option>") Else Response.Write("<option value='NL'>" & "Newfoundland" & "</option>") 
If vendorState = "NS" Then Response.Write("<option selected value='NS'>" & "Nova Scotia" & "</option>") Else Response.Write("<option value='NS'>" & "Nova Scotia" & "</option>") 
If vendorState = "NU" Then Response.Write("<option selected value='NU'>" & "Nunavut" & "</option>") Else Response.Write("<option value='NU'>" & "Nunavut" & "</option>") 
If vendorState = "ON" Then Response.Write("<option selected value='ON'>" & "Ontario" & "</option>") Else Response.Write("<option value='ON'>" & "Ontario" & "</option>")
If vendorState = "PE" Then Response.Write("<option selected value='PE'>" & "Prince Edward Island" & "</option>") Else Response.Write("<option value='PE'>" & "Prince Edward Island" & "</option>") 
If vendorState = "QC" Then Response.Write("<option selected value='QC'>" & "Quebec" & "</option>") Else Response.Write("<option value='QC'>" & "Quebec" & "</option>") 
If vendorState = "SK" Then Response.Write("<option selected value='SK'>" & "Saskatchewan" & "</option>") Else Response.Write("<option value='SK'>" & "Saskatchewan" & "</option>")
If vendorState = "NT" Then Response.Write("<option selected value='NT'>" & "Northwest Territories" & "</option>") Else Response.Write("<option value='NT'>" & "Northwest Territories" & "</option>") 
If vendorState = "YT" Then Response.Write("<option selected value='YT'>" & "Yukon Territory" & "</option>") Else Response.Write("<option value='YT'>" & "Yukon Territory" & "</option>")
%>