<!--#include file="../../../../inc/header.asp"-->
<!--#include file="../../../../inc/mail.asp"-->
<%
If Request.QueryString("custID") = "" Then Response.Redirect ("reports.asp") Else custID = Request.QueryString("custID")

'baseURL should alwats have a trailing /slash, just in case, handle either way
If right(baseURL,1)="/" Then maildomain = Left(right(baseURL,len(baseURL)-7),len(right(baseURL,len(baseURL)-7))-1) Else maildomain = right(baseURL,len(baseURL)-7)


'***********************************
'Post the write quotes query to UNIX
'***********************************
data = "<DATASTREAM>"
data = data & "<IDENTITY>Pm8316wyc011</IDENTITY>"
data = data & "<MODE>" & GetPOSTParams("Mode") & "</MODE>"
data = data & "<RECORD_TYPE>QUOTES</RECORD_TYPE>"
data = data & "<RECORD_SUBTYPE>WRITEQUOTE</RECORD_SUBTYPE>"
data = data & "<SERNO>" & GetPOSTParams("Serno") & "</SERNO>"
data = data & "<ACCOUNT_OR_CHAIN>" & "A" & "</ACCOUNT_OR_CHAIN>"
data = data & "<ACCOUNT_NUM>" & custID & "</ACCOUNT_NUM>"
data = data & "<ITEM_QUOTES>Y</ITEM_QUOTES>" ' 1 True, 0 False
data = data & "<CAT_DISCOUNTS>N</CAT_DISCOUNTS>" 


'***************************************************
''Now construct the XML for all the individual items
''**************************************************

Set cnnQuotedItemsTmp  = Server.CreateObject("ADODB.Connection")
cnnQuotedItemsTmp.open (Session("ClientCnnString"))
Set rsQuotedItemsTmp = Server.CreateObject("ADODB.Recordset")
rsQuotedItemsTmp.CursorLocation = 3 

SQLQuotedItemsTmp = "SELECT * FROM zPRC_AccountQuotedItems_" & trim(Session("Userno")) 
SQLQuotedItemsTmp = SQLQuotedItemsTmp & " ORDER BY prodSKU"
Set rsQuotedItemsTmp = cnnQuotedItemsTmp.Execute(SQLQuotedItemsTmp)

If Not rsQuotedItemsTmp.EOF Then
	Do While Not rsQuotedItemsTmp.EOF
	
		data = data & "<ACCOUNT_QUOTE>"
		
		For x = 0 to rsQuotedItemsTmp.Fields.Count -1
		
			data = data & "<" & UCASE(rsQuotedItemsTmp.Fields(x).Name) & ">"
			
			SELECT CASE UCASE(rsQuotedItemsTmp.Fields(x).Name)
				CASE UCASE("InternalRecordIdentifier")
					data = data & rsQuotedItemsTmp("InternalRecordIdentifier")
				CASE UCASE("RecordCreationDateTime")
					data = data & rsQuotedItemsTmp("RecordCreationDateTime")
				CASE UCASE("prodSKU")
					data = data & rsQuotedItemsTmp("prodSKU")
				CASE UCASE("Description")
					If Not IsNUll(rsQuotedItemsTmp("Description")) Then
						data = data & Server.HTMLEncode(rsQuotedItemsTmp("Description"))
					End IF
				CASE UCASE("Category")
					data = data & rsQuotedItemsTmp("Category")
				CASE UCASE("QuoteType")
					data = data & rsQuotedItemsTmp("QuoteType")
				CASE UCASE("SuggestedQty")
					data = data & rsQuotedItemsTmp("SuggestedQty")
				CASE UCASE("Price")
					data = data & Replace(FormatCurrency(rsQuotedItemsTmp("Price")),",","")
				CASE UCASE("ListFlag")
					If Not ISNull(rsQuotedItemsTmp("ListFlag")) Then
						data = data & rsQuotedItemsTmp("ListFlag")
					End If
				CASE UCASE("Cost")
					data = data & Replace(FormatCurrency(rsQuotedItemsTmp("Cost")),",","")
				CASE UCASE("DateQuoted")
					If Not IsNull(rsQuotedItemsTmp("DateQuoted")) Then
						data = data & rsQuotedItemsTmp("DateQuoted")
					End IF
				CASE UCASE("ExpireDate")
					If Not IsNull(rsQuotedItemsTmp("ExpireDate")) Then
						data = data & rsQuotedItemsTmp("ExpireDate")
					End IF
				CASE UCASE("DeleteFlag")
					If Not IsNull(rsQuotedItemsTmp("DeleteFlag")) Then
						data = data & rsQuotedItemsTmp("DeleteFlag")
					Else
						data = data & "False"
					End IF
				CASE UCASE("NewPrice")
					If Not IsNull(rsQuotedItemsTmp("NewPrice")) Then
						data = data & Replace(FormatCurrency(rsQuotedItemsTmp("NewPrice")),",","")
					Else
						' Must send the the new price if it is being set based on a new GP Percent
						If Not IsNull(rsQuotedItemsTmp.Fields("NewGPPercent")) Then
							NewGPPercentDecimalForCalc = rsQuotedItemsTmp.Fields("NewGPPercent")/100		
							NewPriceForCalc = round(rsQuotedItemsTmp.Fields("Cost")/(1 - NewGPPercentDecimalForCalc),2)
							data = data & Replace(FormatCurrency(NewPriceForCalc),",","")
						End If
					End IF
				CASE UCASE("NewGPPercent")
					If Not IsNull(rsQuotedItemsTmp("NewGPPercent")) Then
						data = data & rsQuotedItemsTmp("NewGPPercent")
					End IF
				CASE UCASE("NewExpireDate")
					If Not IsNull(rsQuotedItemsTmp("NewExpireDate")) Then
						data = data & rsQuotedItemsTmp("NewExpireDate")
					End IF
				CASE UCASE("QuotedToChainOrAccount")
					data = data & rsQuotedItemsTmp("QuotedToChainOrAccount")			
				CASE UCASE("AutoGenerated")
					If Not IsNull(rsQuotedItemsTmp("AutoGenerated")) Then
						data = data & rsQuotedItemsTmp("AutoGenerated")
					Else
						data = data & "False"
					End IF
			END SELECT
			
			data = data & "</" & UCASE(rsQuotedItemsTmp.Fields(x).Name) & ">"
			
		Next 
		
		data = data & "</ACCOUNT_QUOTE>"
		

		rsQuotedItemsTmp.movenext
	Loop
End IF

Set rsQuotedItemsTmp = Nothing
cnnQuotedItemsTmp.Close
Set cnnQuotedItemsTmp  = Nothing

'***************************************************
''End construct the XML for all the individual items
''**************************************************
data = data & "</DATASTREAM>"

'Response.Write("<br><br><br><br>")
'Response.Write(data)
'Response.End

Description = "Post to " & GetPOSTParams("CUSTOMERURL1")
CreateINSIGHTAuditLogEntry Request.ServerVariables("SERVER_NAME"),Description,GetPOSTParams("Mode")

Description = "data:" & data 
CreateINSIGHTAuditLogEntry Request.ServerVariables("SERVER_NAME"),Description,GetPOSTParams("Mode")

Set httpRequest = Server.CreateObject("MSXML2.ServerXMLHTTP")

httpRequest.Open "POST", GetPOSTParams("CUSTOMERURL1"), False
httpRequest.SetRequestHeader "Content-Type", "application/x-www-form-urlencoded"

Err.Clear
On Error Resume Next

httpRequest.Send data

If (Err.Number <> 0 ) Then
	emailbody="httpRequest.status returned " & httpRequest.status & " when posting <RECORD_TYPE>QUOTES and <RECORD_SUBTYPE>WRITEQUOTE"& "<br>"
	emailBody = "httpRequest.responseText:" & httpRequest.responseText & "<br>"
	emailBody = emailBody & "PAGE: " & Request.ServerVariables("SERVER_NAME") & Request.ServerVariables("URL") & "<br>"
	emailBody = emailBody & "Posted to " & GetPOSTParams("CUSTOMERURL1") & "<br>"
	emailBody = emailBody & "POSTED DATA:" & data & "<br>"
	emailBody = emailBody & "SERNO:" & MUV_READ("ClientID") & "<br>"
	SendMail "mailsender@" & maildomain ,"projects@metroplexdata.com",MUV_READ("ClientID") & " QUOTES POST ERROR",emailBody, "Price Tool", "Post Failure"

	Description = emailBody 
	CreateINSIGHTAuditLogEntry Request.ServerVariables("SERVER_NAME"),Description,GetPOSTParams("Mode")

	Response.Redirect("writeQuotesSuccessOrError.asp?custID=" & custID & "&status=error")
End If

On Error Goto 0

	
IF httpRequest.status = 200 THEN 

	If Instr(httpRequest.responseText,"success") <> 0 Then ' Success

		Description ="success! httpRequest.status returned " & httpRequest.status & " when posting <RECORD_TYPE>QUOTES and <RECORD_SUBTYPE>WRITEQUOTE"& "<br>"
		Description = "httpRequest.responseText:" & httpRequest.responseText & "<br>"
		Description = Description & "PAGE: " & Request.ServerVariables("SERVER_NAME") & Request.ServerVariables("URL") & "<br>"
		Description = Description & "Posted to " & GetPOSTParams("CUSTOMERURL1") & "<br>"
		Description = Description & "POSTED DATA:" & data & "<br>"
		Description = Description & "SERNO:" & MUV_READ("ClientID") & "<br>"
		
		CreateINSIGHTAuditLogEntry Request.ServerVariables("SERVER_NAME"),Description,GetPOSTParams("Mode")
		
		'*****************************************
		'Write the info returned from the Post into
		'the temp files before going to next page
		'******************************************
		tmpvar = httpRequest.responseText
		tmpvar=ucase(tmpvar)
		tmpvar = Replace(tmpvar,"SUCCESS","")
		tmpvar = trim(tmpvar)

		Response.Redirect("writeQuotesSuccessOrError.asp?custID=" & custID & "&status=ok")

	Else
		'FAILURE
		emailbody="httpRequest.status returned " & httpRequest.status & " when posting <RECORD_TYPE>QUOTES and <RECORD_SUBTYPE>WRITEQUOTE"& "<br>"
		emailBody = "httpRequest.responseText:" & httpRequest.responseText & "<br>"
		emailBody = emailBody & "PAGE: " & Request.ServerVariables("SERVER_NAME") & Request.ServerVariables("URL") & "<br>"
		emailBody = emailBody & "Posted to " & GetPOSTParams("CUSTOMERURL1") & "<br>"
		emailBody = emailBody & "POSTED DATA:" & data & "<br>"
		emailBody = emailBody & "SERNO:" & MUV_READ("ClientID") & "<br>"
		SendMail "mailsender@" & maildomain ,"insight@ocsaccess.com",MUV_READ("ClientID") & " QUOTES POST ERROR",emailBody, "Price Tool", "Post Failure"
	
		Description = emailBody 
		CreateINSIGHTAuditLogEntry Request.ServerVariables("SERVER_NAME"),Description,GetPOSTParams("Mode")
		
		Response.Redirect("writeQuotesSuccessOrError.asp?custID=" & custID & "&status=error")
	End If
Else

		'FAILURE
		emailbody="NON 200 Response - httpRequest.status returned " & httpRequest.status & " when posting <RECORD_TYPE>QUOTES and <RECORD_SUBTYPE>WRITEQUOTE"& "<br>"
		emailBody = "httpRequest.responseText:" & httpRequest.responseText & "<br>"
		emailBody = emailBody & "PAGE: " & Request.ServerVariables("SERVER_NAME") & Request.ServerVariables("URL") & "<br>"
		emailBody = emailBody & "Posted to " & GetPOSTParams("CUSTOMERURL1") & "<br>"
		emailBody = emailBody & "POSTED DATA:" & data & "<br>"
		emailBody = emailBody & "SERNO:" & MUV_READ("ClientID") & "<br>"
		SendMail "mailsender@" & maildomain ,"insight@ocsaccess.com",MUV_READ("ClientID") & " QUOTES POST ERROR",emailBody, "Price Tool", "Post Failure"
	
		Description = emailBody 
		CreateINSIGHTAuditLogEntry Request.ServerVariables("SERVER_NAME"),Description,GetPOSTParams("Mode")
		
		Response.Redirect("writeQuotesSuccessOrError.asp?custID=" & custID & "&status=error")
End If

%><!--#include file="../../../../inc/footer-main.asp"-->